export type ArchitectureView = "platform" | "mission" | "scale" | "security" | "operations";

export type ArchitecturePlane =
  | "access"
  | "control"
  | "compute"
  | "data"
  | "intelligence"
  | "evidence"
  | "security"
  | "operations";

export type FlowKind = "request" | "control" | "data" | "evidence" | "security";

export type Point = { x: number; y: number };

export type ArchitectureComponent = {
  id: string;
  label: string;
  service: string;
  icon: string | null;
  plane: ArchitecturePlane;
  deployment: "core" | "scale" | "conditional" | "logical";
  positions: Partial<Record<ArchitectureView, Point>>;
  summary: string;
  receives: string;
  processing: string;
  emits: string;
  scaling: string;
  resilience: string;
  security: string;
  evidence: string;
  docsUrl?: string;
};

export type ArchitectureConnection = {
  id: string;
  source: string;
  target: string;
  label: string;
  kind: FlowKind;
  views: ArchitectureView[];
  scaleStage?: number;
};

export type ScaleProfile = {
  id: "1k" | "10k" | "100k" | "1m";
  label: string;
  records: number;
  grants: number;
  partitions: number;
  wallSeconds: number;
  curated: number;
  quarantined: number;
  peakRps: number;
  plannedCost: number;
  accruedCost: number;
};

const AWS = "/aws-icons";

const p = (
  id: string,
  label: string,
  service: string,
  icon: string | null,
  plane: ArchitecturePlane,
  deployment: ArchitectureComponent["deployment"],
  positions: ArchitectureComponent["positions"],
  summary: string,
  receives: string,
  processing: string,
  emits: string,
  scaling: string,
  resilience: string,
  security: string,
  evidence: string,
  docsUrl?: string,
): ArchitectureComponent => ({
  id,
  label,
  service,
  icon,
  plane,
  deployment,
  positions,
  summary,
  receives,
  processing,
  emits,
  scaling,
  resilience,
  security,
  evidence,
  docsUrl,
});

export const ARCHITECTURE_VIEWS: { id: ArchitectureView; label: string; description: string }[] = [
  { id: "platform", label: "Full platform", description: "The end-to-end mission and scale boundaries in one view." },
  { id: "mission", label: "Mission workflow", description: "Every application function and the governed portfolio path." },
  { id: "scale", label: "Production scale", description: "Cost-gated partitions, backpressure, lake processing, intelligence, and export." },
  { id: "security", label: "Network and security", description: "VPC, identity, encryption, private data access, and account security posture." },
  { id: "operations", label: "Operations", description: "Deployment, telemetry, evidence, alarms, tracing, and failure recovery." },
];

export const SCALE_PROFILES: ScaleProfile[] = [
  { id: "1k", label: "1K", records: 1_000, grants: 200, partitions: 6, wallSeconds: 21.351, curated: 989, quarantined: 11, peakRps: 83.33, plannedCost: 0.01898818, accruedCost: 0.01227206 },
  { id: "10k", label: "10K", records: 10_000, grants: 2_000, partitions: 6, wallSeconds: 20.329, curated: 9_891, quarantined: 109, peakRps: 833.33, plannedCost: 0.01915314, accruedCost: 0.01232190 },
  { id: "100k", label: "100K", records: 100_000, grants: 20_000, partitions: 11, wallSeconds: 25.853, curated: 98_921, quarantined: 1_079, peakRps: 5_882.35, plannedCost: 0.03380464, accruedCost: 0.01785423 },
  { id: "1m", label: "1M", records: 1_000_000, grants: 200_000, partitions: 41, wallSeconds: 72.615, curated: 989_852, quarantined: 10_148, peakRps: 16_666.67, plannedCost: 0.13937136, accruedCost: 0.05309299 },
];

export const SCALE_STAGES = [
  { id: 1, label: "Authenticate and plan", detail: "Cognito identity and the protected API establish role and scope, then the server binds an immutable profile, seed, limits, and price evidence. A dedicated presenter identity proves TOTP." },
  { id: 2, label: "Run gate", detail: "The Scale Control function validates plan expiry, idempotency, one-active-run policy, the 100K proof prerequisite, and the cost envelope." },
  { id: 3, label: "Orchestrate", detail: "A Standard Step Functions workflow passes only the run identifier while durable state remains in the DynamoDB ledger." },
  { id: 4, label: "Buffer", detail: "SQS absorbs the partition burst, applies backpressure, retries transient failures, and isolates poison work in a dead letter queue." },
  { id: 5, label: "Generate and gate", detail: "Reserved-concurrency Lambda workers create deterministic related records, validate every row, curate passing data, and quarantine failures." },
  { id: 6, label: "Persist lake zones", detail: "KMS-encrypted S3 stores immutable landing data, curated JSON Lines, quarantine records, receipts, Parquet, and manifests." },
  { id: 7, label: "Catalog and convert", detail: "Six Glue tables expose run partitions. Lake Formation governs access and Athena converts the bounded run to Parquet under a 10 GiB scan cutoff." },
  { id: 8, label: "Merge intelligence", detail: "Finalization merges every idempotent Partition Receipt into full-corpus quality, topic, anomaly, performance, and cost evidence." },
  { id: 9, label: "Release and prove", detail: "The export queue builds an immutable checksummed release while Mission Control reads sanitized terminal evidence from the ledger." },
];

export const COMPONENTS: ArchitectureComponent[] = [
  p("personas", "Mission users", "Portfolio poweruser, scoped viewer, reviewer, and operator", null, "access", "logical", { platform: { x: 0, y: 270 }, mission: { x: 0, y: 260 }, scale: { x: 0, y: 250 }, security: { x: 0, y: 150 } }, "Four personas use one governed mission workspace with role-specific decisions and evidence.", "Human intent over HTTPS.", "The UI presents only capabilities authorized by the verified Cognito group and organization scope.", "Authenticated requests, approvals, Scale Plans, and governed release intent.", "Static CloudFront delivery scales independently from backend work.", "The browser retains the last good projection if live evidence polling is interrupted.", "Password-only team review, a dedicated TOTP presenter path, short-lived JWTs, deny-by-default APIs, and four-eyes release decisions.", "Every mutating decision carries an actor, correlation chain, and audit receipt."),
  p("waf", "Web application firewall", "AWS WAF", `${AWS}/waf.svg`, "security", "core", { platform: { x: 240, y: 90 }, security: { x: 240, y: 20 }, operations: { x: 720, y: 20 } }, "The public edge is screened before any static asset or login path is served.", "Internet requests at the CloudFront distribution.", "Applies AWS managed common protections and a request rate limit.", "Allowed requests to CloudFront and blocked-request metrics to CloudWatch.", "The rate limit bounds abusive request growth before origin load grows.", "Managed rules continue to protect the edge without application changes.", "Attached directly to the distribution. No application route bypass exists.", "Allowed, blocked, and rate-limited requests are observable.", "https://docs.aws.amazon.com/waf/"),
  p("cloudfront", "Mission web edge", "Amazon CloudFront", `${AWS}/cloudfront.svg`, "access", "core", { platform: { x: 240, y: 260 }, mission: { x: 250, y: 20 }, security: { x: 480, y: 20 }, operations: { x: 960, y: 20 } }, "CloudFront delivers the static application globally and enforces the public security boundary.", "HTTPS browser requests and authorized origin fetches.", "Redirects HTTP to HTTPS, rewrites static application paths, applies response security headers, and uses an origin access control.", "Static HTML, JavaScript, CSS, official icon assets, and login redirects.", "Edge caching absorbs frontend traffic without adding Lambda or database load.", "S3 remains private and the edge can continue serving cached assets during origin disturbance.", "WAF, OAC, CSP, HSTS, frame denial, referrer policy, and exact-origin controls.", "Distribution status, access behavior, WAF metrics, and deployment revision.", "https://docs.aws.amazon.com/cloudfront/"),
  p("web-bucket", "Private web origin", "Amazon S3 web bucket", `${AWS}/s3.svg`, "data", "core", { platform: { x: 500, y: 90 }, mission: { x: 520, y: 20 }, security: { x: 720, y: 20 } }, "The statically exported Next.js application is stored in a private S3 origin.", "Versioned frontend build artifacts from the deployment workflow.", "Stores the route folders, assets, official AWS icons, and immutable build output.", "Objects only to CloudFront through origin access control.", "Object delivery scales without application servers.", "S3 durability and repeatable frontend publication provide recovery from a bad client build.", "Block Public Access, encrypted storage, bucket policy limited to the distribution.", "Publication receipt and CloudFront invalidation identify the served revision.", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html"),
  p("cognito", "Identity and optional MFA", "Amazon Cognito", `${AWS}/cognito.svg`, "security", "core", { platform: { x: 240, y: 430 }, mission: { x: 250, y: 190 }, scale: { x: 250, y: 60 }, security: { x: 240, y: 250 } }, "Cognito is the authoritative identity boundary for all interactive users.", "Admin-provisioned identities, passwords, optional TOTP codes, and OIDC authorization requests.", "Authenticates the user and issues short-lived tokens with Compass group membership.", "JWTs for API Gateway and the shared authorization contract.", "Managed identity capacity is separated from the workload data plane.", "Token lifetime is short and users can reauthenticate through the same identity flow.", "MFA is optional at the pool so team reviewers remain unblocked; the dedicated formal presenter identity enrolls TOTP. Self-sign-up is disabled and groups resolve to fixed application roles.", "Authentication assurance and group-derived role are visible without exposing token contents.", "https://docs.aws.amazon.com/cognito/"),
  p("http-api", "Protected service interface", "Amazon API Gateway HTTP API", `${AWS}/api-gateway.svg`, "control", "core", { platform: { x: 500, y: 330 }, mission: { x: 520, y: 210 }, scale: { x: 500, y: 170 }, security: { x: 480, y: 250 }, operations: { x: 240, y: 250 } }, "Thirty-three protected operations across thirty-one paths expose narrow product, document intelligence, MLOps, and Scale Run interfaces.", "Exact-origin HTTPS requests carrying Cognito JWTs.", "Validates the default JWT authorizer, routes by method and path, applies CORS, and records access logs.", "Bound requests to the correct Lambda adapter and sanitized HTTP responses to the browser.", "The stateless API scales per request while heavy work is moved to workflows and queues.", "API failures do not remove durable workflow or run state.", "No unauthenticated data or service operation; the public architecture reference is static, while exact-origin CORS, edge throttling, and a second authorization check protect every API call.", "Access logs, latency, status codes, and 5xx alarms are retained for fourteen days.", "https://docs.aws.amazon.com/apigateway/"),
  p("authorizer", "Identity contract verifier", "AWS Lambda authorizer", `${AWS}/lambda.svg`, "security", "core", { platform: { x: 740, y: 330 }, mission: { x: 780, y: 210 }, security: { x: 720, y: 250 } }, "The custom verifier independently confirms claims before application code derives role and organization.", "The same JWT already checked by API Gateway.", "Checks issuer, signature, expiration, supported groups, role mapping, and organization consistency.", "A normalized deny-by-default identity contract for every function.", "Warm Lambda reuse keeps verification efficient across request volume.", "A token with an unknown group or conflicting organization fails closed.", "Verified groups override forwarded role values and no caller can widen its organization scope.", "Authorization decisions are logged without raw tokens or full claims."),
  p("raw-bucket", "Immutable intake landing", "Amazon S3 raw bucket", `${AWS}/s3.svg`, "data", "core", { platform: { x: 820, y: 100 }, mission: { x: 0, y: 720 } }, "Hash-bound synthetic or authorized source drops enter through one encrypted landing boundary.", "Sanitized JSON objects released under the governed ingest prefix.", "Stores the immutable source object and emits an object-created notification.", "EventBridge event carrying the logical object location.", "S3 absorbs large object arrival independently from workflow compute.", "A failed workflow can replay the same immutable object.", "KMS encryption, Block Public Access, fixed trigger prefix, and no browser-chosen object key.", "Object hash, size, contract version, and ingest correlation are retained.", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"),
  p("eventbridge", "Object event router", "Amazon EventBridge", `${AWS}/eventbridge.svg`, "control", "core", { mission: { x: 250, y: 720 } }, "EventBridge is the single starter for the live intake workflow.", "S3 object-created events from the approved ingest prefix.", "Matches the fixed rule and assumes a narrow role to start the workflow.", "One workflow execution containing only the object reference and correlation metadata.", "Event routing separates bursty arrivals from the application API.", "Failed delivery is visible and the immutable source object remains replayable.", "Only the S3 source and the named Step Functions target are in scope.", "Rule delivery and workflow execution identifiers connect the trace.", "https://docs.aws.amazon.com/eventbridge/"),
  p("intake-workflow", "Governed intake workflow", "AWS Step Functions Express", `${AWS}/step-functions.svg`, "control", "core", { platform: { x: 1060, y: 100 }, mission: { x: 500, y: 720 }, operations: { x: 0, y: 520 } }, "The portfolio-sized path coordinates fetch, validate, quality, persist, and quarantine branches.", "A raw object reference from EventBridge.", "Runs bounded service tasks and records explicit success, quarantine, and failure states.", "Curated database writes, quarantine evidence, lineage, and workflow logs.", "Express orchestration suits frequent short intake executions.", "Branch state is explicit and the raw object is replayable after failure.", "Only references move through state, while database transactions enforce row policy.", "Execution history, application correlation, quality receipt, and terminal state.", "https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html"),
  p("intake", "Normalize and persist", "AWS Lambda intake function", `${AWS}/lambda.svg`, "compute", "core", { mission: { x: 750, y: 650 } }, "The intake adapter normalizes canonical and compatible legacy shapes before persistence.", "Raw JSON objects and a workflow action.", "Fetches, validates manifest metadata, detects adapters, writes raw rows, persists curated rows, or records quarantine lineage.", "Database rows, Kinesis activity receipts, lineage nodes, and bounded workflow results.", "Stateless invocations scale per workflow task and reuse warm database connections.", "Each action is retry-aware and database writes are transactional.", "Private subnet execution, least-privilege S3 and Kinesis access, RLS transaction context.", "Batch, adapter, quality, lineage, and audit identifiers."),
  p("quality", "Quality gate", "AWS Lambda quality function", `${AWS}/lambda.svg`, "compute", "core", { mission: { x: 1000, y: 720 } }, "Deterministic data rules decide whether the batch can enter the governed portfolio.", "Normalized records and the expected fixture or contract metadata.", "Evaluates required fields, types, ranges, duplicates, classification, and relationship rules.", "Rule-level Quality Receipt and a pass or quarantine decision.", "Rules stream over the bounded batch without holding a growing cross-run state.", "A failure produces evidence and no curated rows for the rejected batch.", "No external model is required for the admission decision.", "Scores, passed and failed counts, rule identifiers, and receipt hash."),
  p("ticker", "Operational activity stream", "Amazon Kinesis Data Streams", `${AWS}/kinesis.svg`, "data", "core", { platform: { x: 1540, y: 230 }, mission: { x: 2020, y: 720 } }, "Kinesis carries recent operational signals without replacing the governed database projection.", "Stable activity events from intake and application actions.", "Maintains ordered shards and short-lived transport receipts.", "Recent activity merged by stable event identifier into the product ticker.", "On-demand mode adapts stream capacity to the demonstrated event rate.", "The database projection remains authoritative if a transport receipt is late or missing.", "Missing organization scope is corporate-only and cannot widen a viewer feed.", "Sequence, timestamp, event type, and correlation identifier."),
  p("aurora-writer", "Governed decision store", "Amazon Aurora PostgreSQL writer", `${AWS}/aurora.svg`, "data", "core", { platform: { x: 1300, y: 230 }, mission: { x: 1300, y: 560 }, security: { x: 1530, y: 360 }, operations: { x: 1500, y: 250 } }, "Aurora is the control and decision-serving database for the mission workflow.", "Transactional writes from private application functions.", "Stores raw and curated grants, quality, lineage, topics, anomalies, approvals, licenses, exports, and append-only audit evidence.", "Policy-aware serving projections and durable control state.", "Aurora Serverless v2 adjusts database capacity while functions remain stateless.", "Fourteen-day backups, deletion protection, encryption, and a reader in HA mode.", "Private subnets, Lambda-only security group ingress, FORCE RLS, column grants, and a non-owner runtime role.", "Database readiness, migrations, row counts, quality, model, approval, and audit receipts.", "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html"),
  p("aurora-reader", "HA read replica", "Amazon Aurora PostgreSQL reader", `${AWS}/aurora.svg`, "data", "core", { mission: { x: 1560, y: 560 }, security: { x: 1770, y: 360 }, operations: { x: 1740, y: 250 } }, "A second private Aurora instance provides the deployed HA topology.", "Cluster replication from the writer.", "Maintains a managed replica that can support promotion and read scaling.", "Cluster availability and a failover target.", "Read capacity can scale separately in a production landing zone.", "Managed replication and promotion reduce single-instance exposure.", "The same private subnet group, encryption key, and database security group apply.", "Instance availability and cluster health are monitored."),
  p("bedrock", "In-boundary AI gateway", "Amazon Bedrock adapter", `${AWS}/bedrock.svg`, "intelligence", "core", { platform: { x: 1300, y: 390 }, mission: { x: 2020, y: 170 }, security: { x: 1530, y: 620 } }, "A deployed adapter provides the in-boundary model seam when account model access is enabled.", "Allowlisted prompts or text from private Lambda functions through the shared LLM module.", "Calls allowlisted Nova Lite and Titan Text Embeddings v2 models when enabled, while deterministic paths remain available.", "Model or fallback response, model identifier, grounding citations, and bounded latency evidence.", "Model use is independent from full-corpus deterministic Scale intelligence and can be capped separately.", "Timeouts, retry policy, and deterministic non-LLM paths preserve core workflow behavior.", "No public LLM API, least-privilege model ARNs, and application data remains within the configured AWS service boundary.", "The source contract and fallback receipt are implemented. Final live model-access confirmation remains a demo recording gate.", "https://docs.aws.amazon.com/bedrock/"),
  p("catalog", "Catalog and lineage API", "AWS Lambda catalog function", `${AWS}/lambda.svg`, "compute", "core", { mission: { x: 800, y: 0 } }, "Serves governed datasets, quality metadata, freshness, and run-bound lineage.", "Protected catalog and lineage requests.", "Queries policy-aware Aurora projections and builds sanitized graph contracts.", "Catalog rows and clickable lineage nodes and edges.", "Read-only stateless compute scales with user demand.", "The last persisted catalog and lineage state remains durable in Aurora.", "RLS and CLS apply before the response is shaped.", "Dataset, batch, run, quality, and lineage identifiers."),
  p("analytics", "Topic intelligence API", "AWS Lambda analytics function", `${AWS}/lambda.svg`, "intelligence", "core", { mission: { x: 1040, y: 0 } }, "Runs the portfolio-sized topic model and persists governed intelligence evidence.", "Authorized curated grant abstracts and an explicit poweruser command.", "Uses deterministic topic modeling plus Bedrock embeddings where enabled, then persists topics and model-run metadata.", "Topic assignments, anomaly evidence, model receipt, and lineage.", "Portfolio-sized work remains synchronous; million-row deterministic intelligence uses the separate Scale path.", "A failed model run does not replace the last completed serving projection.", "Poweruser gate, private database access, and allowlisted Bedrock models.", "Corpus size, vocabulary, iterations, reconstruction error, topics, anomalies, and run identifier."),
  p("dashboard", "Decision projection API", "AWS Lambda dashboard function", `${AWS}/lambda.svg`, "compute", "core", { platform: { x: 1060, y: 230 }, mission: { x: 1280, y: 0 } }, "Builds the policy-aware executive decision workspace over the governed Aurora portfolio.", "Protected filters scoped by program area, fiscal year, organization, and search text.", "Computes funding, quality, topic, organization, anomaly, and approval projections inside the caller's transaction context.", "Decision Brief, KPIs, charts, and filter options.", "Short response caching and stateless requests protect the serving database.", "Cached results are isolated by actor, organization, filters, and authorization scope.", "Funding columns remain unreadable for scoped viewers, not merely hidden in the UI.", "Result count, cache outcome, actor scope, and request correlation."),
  p("summarize", "Executive summary API", "AWS Lambda summarize function", `${AWS}/lambda.svg`, "intelligence", "core", { mission: { x: 1520, y: 0 } }, "Produces anomaly lists and an evidence-grounded weekly executive summary.", "Authorized portfolio exceptions and summary requests.", "Reads governed rows, applies deterministic aggregation, and optionally calls Bedrock Nova Lite.", "Summary text, exception counts, model identity, and evidence references.", "Summary generation is bounded separately from ingestion and Scale processing.", "Deterministic evidence remains available if model generation is unavailable.", "RLS scope, private database access, and allowlisted model invocation.", "Source counts, model identifier, outcome, and correlation."),
  p("rag", "Grounded question answering", "AWS Lambda RAG chat function", `${AWS}/lambda.svg`, "intelligence", "core", { mission: { x: 1760, y: 0 } }, "Answers portfolio questions only from grants the caller is allowed to read.", "A question, bounded chat history, and authorized curated grant context.", "Retrieves candidate abstracts under RLS, builds a grounded prompt, and calls Bedrock Nova Lite.", "Answer, citations, snippets, and model identity.", "Retrieval and prompt sizes are bounded so user demand does not become unbounded model spend.", "Returns a grounded no-evidence response when no readable context exists.", "No public model endpoint and no cross-organization retrieval.", "Citation set, grounded status, model ID, and request correlation."),
  p("approvals", "Four-eyes approval API", "AWS Lambda approvals function", `${AWS}/lambda.svg`, "control", "core", { mission: { x: 800, y: 260 } }, "Separates export request and release decisions with an exact, one-time capability.", "A pending export fingerprint and an independent reviewer decision.", "Binds approval to the exact request, stores only a SHA-256 verifier, enforces expiry and separate persona, and consumes the capability once.", "Approved or rejected decision plus a one-time requester handoff token.", "The database row lock serializes competing decisions safely.", "Expiry and one-time consumption prevent replay.", "Reviewer identity must be distinct from the requester and raw capabilities are never persisted.", "Decision actor, subject fingerprint, expiry, state, and audit row."),
  p("license", "License posture API", "AWS Lambda license function", `${AWS}/lambda.svg`, "compute", "core", { mission: { x: 1040, y: 260 } }, "Serves governed entitlements, utilization, cost, owner, and renewal posture.", "Authorized license register requests.", "Reads the RLS-scoped license projection and shapes renewal urgency.", "License posture cards and utilization measures.", "Read-only stateless queries scale with the mission workspace.", "The authoritative license register remains transactional in Aurora.", "Viewer scope and funding-related fields follow database policy.", "Dataset, owner, utilization, renewal, and entitlement evidence."),
  p("export", "Portfolio release API", "AWS Lambda export function", `${AWS}/lambda.svg`, "evidence", "core", { mission: { x: 1280, y: 260 } }, "Creates governed small-portfolio CSV or JSON releases from Aurora.", "Authorized filters, format, requester identity, and approval capability when required.", "Rechecks RLS and CLS, applies the aggregation guard, consumes approval atomically, and writes audit evidence.", "Downloadable release and immutable audit receipt.", "Large Scale Run releases use the asynchronous lake Export Job instead of this synchronous adapter.", "Exact fingerprinting and one-time approval make retries safe.", "Row and column policy is evaluated again at release time.", "Rows, bytes, format, checksum, actor, policy result, and audit identifier."),
  p("evidence", "System evidence API", "AWS Lambda evidence function", `${AWS}/lambda.svg`, "evidence", "core", { mission: { x: 1520, y: 260 }, operations: { x: 240, y: 520 } }, "Projects sanitized backend proof for Mission Control without exposing physical infrastructure identifiers.", "A protected poweruser evidence request.", "Reads allowlisted application projections for deployment, runs, stages, audit, model, API, database, and Scale state.", "System Inspector snapshot with correlation, latency, stage trace, and mode disclosure.", "Compact projections avoid scanning raw logs or the lake during interaction.", "The browser keeps the last good snapshot when polling is interrupted.", "Poweruser only and an explicit denylist for secrets, tokens, ARNs, account IDs, raw records, and stack traces.", "Deployment revision, generation time, checks, run traces, and policy decisions."),
  p("rmf", "RMF artifact generator", "AWS Lambda RMF artifact function", `${AWS}/lambda.svg`, "evidence", "core", { mission: { x: 1760, y: 260 } }, "Generates candidate security documentation from the deployed template and application evidence.", "A protected request and the current approved architecture contract.", "Maps services and controls into a bounded RMF-oriented artifact without using an LLM.", "Candidate architecture and control evidence for human review.", "Artifact creation is asynchronous from mission operations and does not affect serving capacity.", "A deterministic template can be reproduced from source.", "Poweruser gate and sanitized resource references.", "Template revision, service mapping, generated sections, and receipt."),
  p("migrator", "Schema and demo preparation", "AWS Lambda migrator function", `${AWS}/lambda.svg`, "control", "core", { mission: { x: 1040, y: 470 }, operations: { x: 480, y: 520 } }, "Applies additive migrations and performs the bounded, operator-confirmed synthetic baseline preparation.", "Deployment migration payloads or a confirmed operator preparation command.", "Runs versioned SQL, bootstraps the non-owner runtime role, validates fixtures, and prepares the deterministic 400-grant baseline.", "Migration result or redacted readiness receipt.", "It is invoked operationally, not exposed as a public API.", "Additive migration order and transactional reset preserve a recoverable release path.", "Private database access and a narrow invocation principal.", "Applied migration IDs, runtime-role grant state, fixture hashes, and 19 readiness checks."),
  p("scale-control", "Scale Plan and Run Gate", "AWS Lambda Scale Control", `${AWS}/lambda.svg`, "control", "scale", { platform: { x: 820, y: 590 }, scale: { x: 760, y: 170 }, operations: { x: 480, y: 250 } }, "The Scale Run Module exposes the narrow plan, launch, status, cancel, and export interface.", "A corporate poweruser command with a fixed profile, seed, and idempotency key.", "Calculates price-backed cost, enforces profile and concurrency limits, validates prerequisites, writes the durable run, and starts orchestration.", "A Scale Plan or sanitized Scale Run projection.", "One active run and deployment-controlled maximums prevent the browser from expanding capacity without review.", "Idempotency keys and conditional ledger writes prevent duplicate launches.", "Corporate poweruser policy, no physical resource identifiers in responses, and a hard maximum estimated cost.", "Plan, cost envelope, gate decision, run ID, revision, and correlation.", "https://docs.aws.amazon.com/lambda/"),
  p("scale-workflow", "Durable Scale lifecycle", "AWS Step Functions Standard", `${AWS}/step-functions.svg`, "control", "scale", { platform: { x: 1060, y: 590 }, scale: { x: 1010, y: 170 }, operations: { x: 0, y: 700 } }, "A Standard workflow coordinates partition dispatch, completion, Athena conversion, finalization, cancellation, and failure compensation.", "Only the Scale Run identifier from the Run Gate.", "Reads durable ledger state at each boundary and starts the next bounded action.", "Queue work, Athena queries, terminal manifests, or guarded failure state.", "State payload stays constant while the partition count rises from 6 to 41.", "Standard history, retries, timeouts, and explicit cancel and failure branches.", "The role is limited to the Scale queues, table, lake, Glue, Athena, KMS, and Scale functions.", "Execution history, transitions, terminal state, and workflow logs.", "https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html"),
  p("scale-ledger", "Run and partition ledger", "Amazon DynamoDB", `${AWS}/dynamodb.svg`, "data", "scale", { platform: { x: 1300, y: 720 }, scale: { x: 1010, y: 470 }, operations: { x: 720, y: 520 } }, "DynamoDB is the durable idempotency and Serving Projection boundary for Scale Runs.", "Plans, run state, partition leases, receipts, progress, costs, and cancellation requests.", "Uses conditional and transactional updates so one terminal partition contributes counts once.", "Compact Scale Run snapshots, progress, recovery depth, and terminal evidence.", "On-demand capacity grows with partition activity and avoids a database hot path for the lake workload.", "Every transition is conditional and a retry observes the existing terminal receipt.", "KMS encryption, point-in-time recovery, time-to-live, and least-privilege key access.", "Plan consumption, partition receipt hashes, counts, duplicates, cost, and state transition timestamps.", "https://docs.aws.amazon.com/amazondynamodb/"),
  p("worker-queue", "Partition backpressure", "Amazon SQS worker queue", `${AWS}/sqs.svg`, "data", "scale", { platform: { x: 1320, y: 520 }, scale: { x: 1260, y: 170 }, operations: { x: 960, y: 520 } }, "The worker queue turns a partition burst into bounded parallel work.", "One deterministic message for each planned dataset partition.", "Holds messages until reserved Lambda capacity is available and retries transient failures under a redrive policy.", "Partition work to the Scale Worker and failed messages to the worker dead letter queue.", "Queue depth grows while worker concurrency remains fixed at four by default.", "Visibility timeout and redrive isolate slow or poison partitions without losing the run.", "SSE-KMS and resource policies limit send and consume principals.", "Visible depth, in-flight count, age of oldest message, retries, and DLQ depth.", "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html"),
  p("worker-dlq", "Worker recovery queue", "Amazon SQS dead letter queue", `${AWS}/sqs.svg`, "evidence", "scale", { scale: { x: 1260, y: 430 }, operations: { x: 1200, y: 650 } }, "Repeatedly failing partition work is isolated for operator inspection and controlled redrive.", "Messages that exhaust the worker queue redrive policy.", "Retains the failed partition envelope without changing terminal counts.", "Operator recovery evidence and a redrive candidate.", "Failure isolation prevents a poison partition from consuming all worker capacity.", "The main queue continues processing healthy partitions.", "Encrypted queue and no browser access.", "DLQ depth alarm, message age, run correlation, and partition identifier."),
  p("scale-worker", "Deterministic partition workers", "AWS Lambda Scale Worker", `${AWS}/lambda.svg`, "compute", "scale", { platform: { x: 1570, y: 520 }, scale: { x: 1510, y: 170 }, operations: { x: 1200, y: 520 } }, "Workers generate, validate, curate, quarantine, aggregate, hash, and receipt each bounded partition.", "A dataset, range, seed, profile, contract version, and run identifier from SQS.", "Streams deterministic related records to compressed JSON Lines, evaluates rules record by record, and commits one terminal receipt transaction.", "Landing, curated, and quarantine objects plus aggregate partials and a Partition Receipt.", "No partition exceeds 25,000 records and reserved concurrency defaults to four, so memory and downstream pressure stay bounded as total records grow.", "At-least-once delivery is safe because a retry verifies deterministic output and cannot increment totals twice.", "Runs outside the VPC with only SQS, DynamoDB, S3, KMS, and CloudWatch access.", "Checksums, records, bytes, issues, duration, retry evidence, and aggregate partials."),
  p("scale-lake", "Governed Scale Run lake", "Amazon S3 data lake", `${AWS}/s3.svg`, "data", "scale", { platform: { x: 1810, y: 520 }, scale: { x: 1760, y: 170 }, security: { x: 1770, y: 620 } }, "The encrypted lake is the durable system of record for production-scale synthetic workloads.", "Worker streams, Athena outputs, intelligence receipts, export manifests, and evidence.", "Separates immutable landing, curated, quarantine, receipts, Parquet, evidence, and release zones by run and dataset.", "Partitioned objects for Glue and Athena plus logical locators for the product.", "Object count and bytes grow with the profile while computation remains partitioned and pay per use.", "Versioning, lifecycle expiry, and immutable source parts make the workload replayable.", "Block Public Access, bucket policy, SSE-KMS, synthetic-only metadata, and no physical key disclosure to the browser.", "Object bytes, ETags, SHA-256 values, partition manifests, and terminal run manifest.", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"),
  p("glue", "Six-dataset catalog", "AWS Glue Data Catalog", `${AWS}/glue.svg`, "intelligence", "scale", { platform: { x: 2050, y: 380 }, scale: { x: 2010, y: 40 } }, "Glue defines grants, finance, milestones, documents, licenses, and stream events over run-partitioned lake data.", "Completed curated object partitions and schema definitions.", "Registers run partitions without moving the data.", "Queryable tables for the bounded Athena workgroup.", "Metadata grows by run and partition rather than by individual record.", "The underlying S3 objects remain authoritative and can be recataloged.", "Lake Formation grants and Glue permissions restrict table access.", "Database, table, partition, schema, and run association.", "https://docs.aws.amazon.com/glue/"),
  p("lake-formation", "Lake access policy", "AWS Lake Formation", `${AWS}/lake-formation.svg`, "security", "scale", { scale: { x: 2010, y: 300 }, security: { x: 2010, y: 620 } }, "Lake Formation gives the Scale Control role explicit database and table access.", "Glue database and six table resources plus the authorized principal.", "Applies database DESCRIBE and table SELECT permissions.", "Governed catalog authorization for Athena operations.", "Permissions remain table-scoped as partitions increase.", "A recatalog or new run does not require broad bucket access for the browser.", "Named principal grants, least privilege, and no anonymous lake access.", "Principal, resource, permission, and grant state."),
  p("athena", "Bounded columnar conversion", "Amazon Athena", `${AWS}/athena.svg`, "intelligence", "scale", { platform: { x: 2290, y: 380 }, scale: { x: 2260, y: 40 }, operations: { x: 1440, y: 520 } }, "Athena converts each completed curated dataset to compressed Parquet and records scan evidence.", "Six run-partitioned Glue tables.", "Runs partition-pruned CTAS work inside a dedicated workgroup with a 10 GiB per-query scan cutoff.", "Parquet objects, query state, scanned bytes, output bytes, and checksums.", "Pay-per-scan work grows with the selected run while idle infrastructure stays minimal.", "The workflow polls durable query state and fails the run if any conversion fails or is cancelled.", "KMS result encryption, workgroup enforcement, Lake Formation permissions, and a hard bytes-scanned cutoff.", "Query identifiers, state, data scanned, output files, bytes, and terminal receipt.", "https://docs.aws.amazon.com/athena/"),
  p("export-queue", "Asynchronous release buffer", "Amazon SQS export queue", `${AWS}/sqs.svg`, "data", "scale", { platform: { x: 2050, y: 650 }, scale: { x: 2260, y: 300 }, operations: { x: 1680, y: 520 } }, "Completed Scale Run release requests are isolated from interactive API latency.", "One idempotent export request for a completed run.", "Buffers release work and applies an independent redrive policy.", "Export job message to the Scale Export worker or failed work to the export DLQ.", "Reserved export concurrency can be tuned separately from partition generation.", "A release retry does not block the Scale API or mutate source Parquet objects.", "SSE-KMS and named send and consume principals.", "Queue depth, message age, retry, DLQ depth, and export idempotency key."),
  p("export-dlq", "Export recovery queue", "Amazon SQS dead letter queue", `${AWS}/sqs.svg`, "evidence", "scale", { scale: { x: 2260, y: 550 }, operations: { x: 1920, y: 650 } }, "Repeatedly failing release work is retained for controlled recovery.", "Export messages that exhaust the redrive policy.", "Isolates the failure without altering the completed run or its source objects.", "Operator evidence and a redrive candidate.", "Export failures cannot consume worker capacity indefinitely.", "The completed Scale Run and Parquet outputs remain intact.", "Encrypted and inaccessible to the browser.", "DLQ alarm, failed export identifier, run correlation, and age."),
  p("scale-export", "Governed lake Export Job", "AWS Lambda Scale Export", `${AWS}/lambda.svg`, "evidence", "scale", { platform: { x: 2290, y: 650 }, scale: { x: 2510, y: 300 }, operations: { x: 1920, y: 520 } }, "The asynchronous worker seals the exact Parquet release for a completed Scale Run.", "A completed run, requested dataset, Parquet format, and idempotency key.", "Verifies terminal state and source objects, builds a checksummed manifest, records rows and bytes, and writes the receipt.", "Immutable governed release manifest and sanitized Export Receipt.", "Release capacity is independent from ingestion workers and interactive APIs.", "Idempotency prevents duplicate logical releases and source objects are immutable.", "Least-privilege lake and ledger access, SSE-KMS, no raw physical locators in the browser.", "Rows, bytes, format, SHA-256, logical object, expiration, actor, and audit receipt."),
  p("vpc", "Private application network", "Amazon VPC", `${AWS}/vpc.svg`, "security", "core", { security: { x: 960, y: 360 } }, "One VPC spans two availability zones and separates public egress from private application and database access.", "Network traffic from private Lambda functions and managed database interfaces.", "Routes private application egress through one cost-controlled NAT gateway while keeping Aurora non-public.", "Controlled TLS paths to AWS APIs, Bedrock, Secrets Manager, and Aurora.", "Additional NAT gateways, endpoints, or subnets can be added in the target landing zone without changing application interfaces.", "Two-AZ private and public subnet layout and managed service durability.", "Security groups allow database ingress only from the Lambda security group on PostgreSQL port 5432.", "Subnet placement, route association, security group path, and private database posture.", "https://docs.aws.amazon.com/vpc/"),
  p("internet-gateway", "Public egress boundary", "Amazon VPC internet gateway", `${AWS}/internet-gateway.svg`, "security", "core", { security: { x: 720, y: 500 } }, "The internet gateway attaches the public route table to the VPC edge.", "Outbound and return traffic for public subnet resources.", "Provides the routable boundary used by the NAT gateway.", "Controlled egress path for private application traffic.", "The gateway is horizontally scaled by the managed VPC service.", "It has no direct route to private database resources.", "Only public route tables reference it and Aurora remains non-public.", "Attachment and route state."),
  p("public-subnets", "Two public subnets", "Amazon VPC subnets", `${AWS}/vpc.svg`, "security", "core", { security: { x: 960, y: 500 } }, "One public subnet in each availability zone hosts the egress routing boundary.", "Route table association and NAT gateway placement.", "Provides the zonal public network layer for controlled outbound connectivity.", "NAT egress to the internet gateway.", "A production landing zone can use one NAT per AZ for stronger zonal isolation.", "Two-AZ layout reduces dependence on one subnet.", "No application Lambda or Aurora interface is public.", "Subnet and route table associations."),
  p("nat-gateway", "Cost-controlled egress", "Amazon VPC NAT gateway", `${AWS}/nat-gateway.svg`, "security", "core", { security: { x: 1200, y: 500 } }, "One NAT gateway provides outbound access for private functions in the deployed demonstration.", "Private subnet traffic for Bedrock and AWS service APIs that lack a local endpoint in this stack.", "Translates outbound connections through one elastic IP.", "TLS egress and return traffic without inbound internet reachability.", "A target HA design can deploy one NAT per AZ or replace paths with VPC endpoints.", "Managed NAT is durable within its availability zone, while the documented production target removes the single-AZ dependency.", "No unsolicited inbound path and security groups still govern function traffic.", "Bytes, connections, errors, and route state."),
  p("private-subnets", "Two private subnets", "Amazon VPC subnets", `${AWS}/vpc.svg`, "security", "core", { security: { x: 1200, y: 360 } }, "Application functions and Aurora network interfaces are isolated from direct internet routing.", "API-triggered Lambda network interfaces and Aurora cluster traffic.", "Routes outbound service calls through NAT and internal database traffic through security groups.", "Private TLS and PostgreSQL connections.", "Lambda concurrency can grow across both subnets and Aurora can place instances across both AZs.", "Two availability zones and managed ENI placement support service continuity.", "No public IPs and no internet gateway route.", "Subnet identifiers are retained in stack evidence but not exposed to the browser."),
  p("lambda-sg", "Application security group", "Amazon VPC security group", `${AWS}/vpc.svg`, "security", "core", { security: { x: 1440, y: 360 } }, "The application security group is the only database client network identity.", "Private function network interfaces.", "Allows controlled egress and identifies the source accepted by the database group.", "TLS service calls and PostgreSQL sessions.", "New function ENIs inherit the same narrow policy.", "Security group references survive IP changes and Lambda scaling.", "No broad database CIDR rule.", "Ingress and egress rule state."),
  p("db-sg", "Database security group", "Amazon VPC security group", `${AWS}/vpc.svg`, "security", "core", { security: { x: 1530, y: 500 } }, "The database accepts PostgreSQL only from the application security group.", "TCP 5432 sessions from approved private Lambda functions.", "Rejects every other inbound network source.", "Private Aurora connection only.", "Policy remains constant as Lambda IPs and concurrency change.", "Reference-based rules avoid fragile address lists.", "No public CIDR ingress and no public database endpoint.", "Rule source, port, and database network posture."),
  p("kms", "Customer-managed encryption", "AWS Key Management Service", `${AWS}/kms.svg`, "security", "core", { platform: { x: 1540, y: 80 }, security: { x: 1200, y: 80 }, operations: { x: 1440, y: 20 } }, "One rotating customer-managed key protects the application data plane and evidence stores.", "Encrypt and decrypt requests from approved services and roles.", "Provides envelope encryption for S3, SQS, DynamoDB, logs, and database-related secrets.", "Encrypted objects, messages, ledger items, and logs.", "Managed cryptographic throughput is independent from application worker count.", "Key rotation is enabled and data services retain encrypted durability.", "Key policy limits principals and every service still requires its own IAM authorization.", "KMS request quantities are included in Scale cost evidence.", "https://docs.aws.amazon.com/kms/"),
  p("secrets", "Database secret", "AWS Secrets Manager", `${AWS}/secrets-manager.svg`, "security", "core", { security: { x: 1770, y: 80 } }, "Aurora manages the master credential in Secrets Manager while runtime functions use the non-owner application role.", "Credential lifecycle from the managed Aurora cluster and authorized migration functions.", "Stores and returns encrypted secret material only to narrow execution roles.", "Short-lived application initialization material inside private Lambda execution.", "Warm connections reduce repeated secret retrieval as request volume grows.", "The managed secret remains independent from application deployments.", "KMS encryption and no secret value is logged, returned, or placed in source.", "Secret ARN is an operator-only output and access is auditable.", "https://docs.aws.amazon.com/secretsmanager/"),
  p("iam", "Least-privilege service roles", "AWS Identity and Access Management", `${AWS}/iam.svg`, "security", "core", { security: { x: 960, y: 80 }, operations: { x: 480, y: 20 } }, "Each Lambda, workflow, event rule, CloudFront origin control, and deployment path receives a scoped service identity.", "Trusted service assumptions and reviewed deployment role sessions.", "Evaluates resource and action permissions for every AWS API call.", "Allow or deny decisions at each adapter boundary.", "Role policy does not widen when records or partitions increase.", "Short-lived OIDC deployment sessions remove long-lived repository access keys.", "Explicit resources, separate execution roles, and deny-by-default application authorization.", "Assumed role, action, resource, and deployment revision."),
  p("cloudwatch-logs", "Centralized runtime logs", "Amazon CloudWatch Logs", `${AWS}/cloudwatch.svg`, "operations", "core", { operations: { x: 720, y: 250 } }, "API, workflow, and application functions emit structured operational records into named fourteen-day log groups.", "Access events, workflow histories, application logs, and error signals.", "Separates API, function, intake workflow, and Scale workflow streams.", "Searchable operational evidence and alarm metrics.", "Log ingestion grows with workload activity and remains priced in the Scale cost model.", "Retention prevents unbounded storage and independent groups isolate noisy components.", "KMS encryption where configured and application logs exclude protected identifiers and secrets.", "Request ID, correlation, function, route, status, duration, and bounded error category."),
  p("cloudwatch-alarms", "Thirteen health alarms", "Amazon CloudWatch Alarms", `${AWS}/cloudwatch.svg`, "operations", "core", { operations: { x: 960, y: 250 } }, "Alarms cover API errors, function failures, all workflows, Scale workers, DLQs, and worker queue age.", "Service metrics and log-derived operational signals.", "Evaluates fixed thresholds and exposes OK, ALARM, or insufficient-data state.", "Operator health state and incident signal.", "Metrics aggregate across runs without using high-cardinality run IDs.", "A single component failure remains visible even when the UI continues serving cached assets.", "Alarm definitions are versioned in the SAM template.", "State transition, metric, threshold, evaluation period, and timestamp."),
  p("cloudwatch-dashboards", "Two operations dashboards", "Amazon CloudWatch Dashboards", `${AWS}/cloudwatch.svg`, "operations", "core", { operations: { x: 1200, y: 250 } }, "One dashboard covers the mission application and one covers Scale control, queues, workers, workflow, and cost signals.", "CloudWatch metrics and alarm state.", "Presents operational rates, errors, duration, queue depth, age, and workflow outcomes.", "A shared operator view independent from the product UI.", "Widgets aggregate service signals as request and record volume changes.", "The dashboards remain available even if the application frontend has a data error.", "CloudWatch IAM controls operator access.", "Metric series, time range, alarm state, and dashboard revision."),
  p("xray", "Distributed tracing", "AWS X-Ray", `${AWS}/x-ray.svg`, "operations", "core", { operations: { x: 1440, y: 250 }, security: { x: 2010, y: 360 } }, "Tracing connects API and Lambda segments for latency and failure diagnosis.", "Sampled service requests and Lambda subsegments.", "Builds a service map and traces request latency across the protected interface.", "Trace identifiers and sampled dependency timing.", "Sampling bounds tracing overhead while retaining representative behavior.", "A trace can identify the failing seam without logging record contents.", "Trace data is operational evidence and not exposed through the browser.", "Trace ID, segment, duration, fault, error, and throttle state.", "https://docs.aws.amazon.com/xray/"),
  p("guardduty", "Threat detection", "Amazon GuardDuty", `${AWS}/guardduty.svg`, "security", "conditional", { security: { x: 240, y: 700 }, operations: { x: 720, y: 700 } }, "The optional security baseline enables managed threat detection at the AWS account boundary.", "Supported AWS control-plane and data-source telemetry.", "Analyzes activity for suspicious behavior and produces findings.", "Account security findings for operator review.", "Managed detection scales with account telemetry.", "The application remains functional if the optional detector is disabled in a constrained demo account.", "Account-level managed service with no application data returned to end users.", "Finding type, severity, resource class, and time.", "https://docs.aws.amazon.com/guardduty/"),
  p("securityhub", "Security posture aggregation", "AWS Security Hub", `${AWS}/security-hub.svg`, "security", "conditional", { security: { x: 480, y: 700 }, operations: { x: 960, y: 700 } }, "The optional baseline centralizes security findings and standards posture.", "GuardDuty, service findings, and enabled security controls.", "Normalizes findings into a shared security posture view.", "Prioritized operator findings.", "Managed aggregation grows with enabled controls rather than application record count.", "Application controls remain in place independently from account-level aggregation.", "Operator-only account service.", "Control status, finding severity, resource type, and workflow state.", "https://docs.aws.amazon.com/securityhub/"),
  p("macie", "Sensitive-data discovery", "Amazon Macie", `${AWS}/macie.svg`, "security", "conditional", { security: { x: 720, y: 700 }, operations: { x: 1200, y: 700 } }, "The optional baseline enables managed S3 sensitive-data discovery posture.", "S3 inventory and configured discovery activity.", "Classifies supported sensitive-data patterns and produces findings.", "Operator-only findings and bucket posture.", "Discovery can be scheduled and scoped independently from workload processing.", "The application labels all demonstration data synthetic regardless of Macie status.", "No finding details are projected into the public product.", "Bucket posture, job status, finding category, and severity.", "https://docs.aws.amazon.com/macie/"),
  p("document-ml", "Document Intake and MLOps Adapter", "AWS Lambda document ML function", `${AWS}/lambda.svg`, "compute", "core", { platform: { x: 740, y: 560 }, mission: { x: 750, y: 900 }, operations: { x: 1680, y: 520 } }, "One deep Module exposes narrow upload, run, training, registry, promotion, and drift Interfaces while hiding the selected compute Implementation.", "Protected browser upload plans, document events, fixed workflow actions, and model operation requests.", "Validates files, extracts bounded content, applies quality, trains the shared classical taxonomy, classifies, and seals evidence.", "Document, model, deployment, drift, and lineage receipts with logical locators.", "Browser calls remain small while event workflows and bounded training run asynchronously.", "Immutable source and idempotent run records allow retry and replay.", "Corporate poweruser gate, safe file names, strict media types, KMS, least privilege, and synthetic-only policy.", "Hashes, stage state, metrics, model version, alias, and drift action.", "https://docs.aws.amazon.com/lambda/"),
  p("document-workflow", "Document processing workflow", "AWS Step Functions Express", `${AWS}/step-functions.svg`, "control", "core", { platform: { x: 980, y: 560 }, mission: { x: 1000, y: 900 }, operations: { x: 1920, y: 700 } }, "The document workflow makes inspect, quality, curate, and quarantine transitions visible and retryable.", "An S3 object-created event for the approved incoming prefix.", "Invokes fixed document actions, branches on the quality gate, and records one terminal result.", "Bronze, Silver, Gold, quarantine, and workflow evidence.", "Express execution absorbs independent document arrivals without holding browser connections.", "The source object remains immutable and failed stages can be replayed.", "Only logical references and bounded metadata cross states; execution data is excluded from logs.", "Execution ARN, state transition, duration, retry, and terminal receipt.", "https://docs.aws.amazon.com/step-functions/"),
  p("document-ledger", "Document and model ledger", "Amazon DynamoDB", `${AWS}/dynamodb.svg`, "evidence", "core", { platform: { x: 1220, y: 560 }, mission: { x: 1250, y: 900 }, operations: { x: 2160, y: 700 } }, "A retained, encrypted ledger stores document runs and complete model lifecycle receipts without exposing physical storage keys.", "Idempotent document, model, deployment, alias, and drift records.", "Applies conditional writes and a type index for bounded evidence queries.", "Sanitized state projections for Compass and immutable correlation records for operators.", "On-demand capacity scales with run and evidence volume.", "Point-in-time recovery and conditional state transitions protect the control history.", "KMS encryption and function-only least-privilege access.", "Actor, timestamp, digest, model version, status, and logical URI."),
  p("sagemaker", "SageMaker training Adapter", "Amazon SageMaker training and Model Registry", null, "intelligence", "conditional", { platform: { x: 1460, y: 560 }, mission: { x: 1500, y: 900 }, operations: { x: 1920, y: 520 } }, "The production Adapter submits bounded network-isolated training and retains governed model packages while the deterministic Adapter preserves the same contract for rehearsal.", "Approved synthetic training manifest, image, execution role, algorithm parameters, and output prefix.", "Runs classical training, evaluates fixed gates, registers an immutable candidate, and waits for human approval.", "Metrics, artifacts, package version, approval state, and deployment input.", "Training instances are bounded by one job, one instance, a hard runtime, and explicit cost control.", "Failure leaves the current Champion unchanged and artifacts replayable.", "Network isolation, inter-container encryption, KMS, exact S3 prefixes, and a dedicated execution role.", "Job ARN, package version, metrics, artifact digest, and approval transition.", "https://docs.aws.amazon.com/sagemaker/"),
  p("model-monitor", "Drift and retraining control", "Compass monitoring receipts", `${AWS}/cloudwatch.svg`, "intelligence", "core", { platform: { x: 1700, y: 560 }, mission: { x: 1750, y: 900 }, operations: { x: 2160, y: 520 } }, "Model monitoring compares bounded inference evidence to the accepted training baseline and never replaces a model without review.", "Class distributions, vocabulary coverage, confidence, current Champion, and approved thresholds.", "Calculates drift, creates a recommended action, and opens a Candidate retraining path when thresholds fail.", "Drift Receipt, review task, Candidate version, and retained Champion state.", "Monitoring works by bounded batches and does not require an always-on endpoint.", "The Champion remains available when evaluation or retraining fails.", "Thresholds and promotion are policy-controlled, with no automatic silent production change.", "PSI, out-of-vocabulary rate, mean confidence, action, and reviewer decision."),
  p("github-actions", "DevSecOps delivery pipeline", "GitHub Actions with AWS OIDC", null, "operations", "core", { operations: { x: 0, y: 900 }, security: { x: 0, y: 900 } }, "The golden pipeline binds source, security, tests, IaC, approval, deployment, DAST, smoke checks, and rollback evidence to one revision.", "Pull request, reviewed commit, protected environment decision, and short-lived OIDC identity.", "Runs secret, SAST, dependency, SBOM, IaC, STIG policy, contract, browser, and post-deploy gates.", "A Delivery Receipt and a promoted application revision.", "Hosted runners parallelize independent gates while deployment remains serialized.", "Failed gates stop promotion and the previous static build and stack revision remain recoverable.", "No long-lived cloud keys, least-privilege role session, reviewed environment, and immutable workflow source.", "Commit, plan digest, scan results, reviewer, deployment result, and smoke receipt."),
  p("terraform", "AWS foundation modules", "Terraform plus SAM application modules", null, "operations", "core", { operations: { x: 240, y: 900 }, security: { x: 240, y: 900 } }, "Terraform defines the account and integration foundation while SAM defines the event-driven application, with ownership boundaries preventing two sources from managing one resource.", "Versioned modules, environment variables, policy checks, and reviewed parameters.", "Plans the foundation, validates the application graph, and produces an inspectable change set.", "Reproducible infrastructure and a plan digest bound to deployment approval.", "Modules compose by stable outputs and independent state boundaries.", "State locking, change sets, rollback, and rebuild-from-source support recovery.", "Encrypted remote state target, no committed secrets, static policy checks, and OIDC deployment.", "Module revision, plan, change set, stack events, and outputs."),
  p("cloudformation", "Versioned infrastructure", "AWS CloudFormation and SAM", `${AWS}/cloudformation.svg`, "operations", "core", { security: { x: 0, y: 700 }, operations: { x: 0, y: 20 } }, "The complete application, data, network, security, workflow, observability, and edge shape is defined as one reviewable SAM stack.", "Reviewed template, parameters, migration payload, container artifacts, and short-lived deployment identity.", "Builds, changes, and reports the declared infrastructure graph.", "A reproducible stack and deployment outputs used to build the frontend.", "Conditional Scale resources and protected limits allow one template to support bounded deployment modes.", "Change sets, rollback, additive migrations, and source reproducibility provide recovery paths.", "GitHub OIDC, protected environment review, parameter validation, and no long-lived cloud keys in the repository.", "Stack state, resource events, deployment revision, outputs, migration receipts, and frontend publication checks.", "https://docs.aws.amazon.com/cloudformation/"),
];

const e = (
  source: string,
  target: string,
  label: string,
  kind: FlowKind,
  views: ArchitectureView[],
  scaleStage?: number,
): ArchitectureConnection => ({ id: `${source}-${target}-${views.join("-")}`, source, target, label, kind, views, scaleStage });

export const CONNECTIONS: ArchitectureConnection[] = [
  e("personas", "waf", "HTTPS", "request", ["platform", "security"]),
  e("waf", "cloudfront", "allowed request", "security", ["platform", "security", "operations"]),
  e("cloudfront", "web-bucket", "OAC origin fetch", "data", ["platform", "mission", "security"]),
  e("personas", "cognito", "OIDC plus TOTP", "security", ["platform", "mission", "scale", "security"], 1),
  e("cognito", "http-api", "short-lived JWT", "request", ["platform", "mission", "scale", "security"], 1),
  e("http-api", "authorizer", "verify claims", "security", ["platform", "mission", "security"], 1),
  e("authorizer", "dashboard", "normalized identity", "request", ["platform", "mission"]),
  e("authorizer", "scale-control", "corporate poweruser", "request", ["platform", "scale"], 2),
  e("http-api", "document-ml", "upload and model operations", "request", ["platform", "mission", "operations"]),
  e("raw-bucket", "document-workflow", "document object created", "control", ["platform", "mission"]),
  e("document-workflow", "document-ml", "inspect, quality, curate", "control", ["platform", "mission", "operations"]),
  e("document-ml", "raw-bucket", "Bronze, Silver, Gold, artifacts", "data", ["platform", "mission"]),
  e("document-ml", "document-ledger", "lifecycle receipts", "evidence", ["platform", "mission", "operations"]),
  e("document-ml", "sagemaker", "bounded training request", "control", ["platform", "mission", "operations"]),
  e("sagemaker", "document-ledger", "model package evidence", "evidence", ["platform", "mission", "operations"]),
  e("document-ledger", "model-monitor", "Champion and inference baseline", "data", ["platform", "mission", "operations"]),
  e("model-monitor", "document-ml", "drift and retraining action", "control", ["platform", "mission", "operations"]),
  e("raw-bucket", "eventbridge", "object created", "control", ["mission"]),
  e("eventbridge", "intake-workflow", "start execution", "control", ["mission"]),
  e("intake-workflow", "intake", "fetch and persist tasks", "control", ["mission"]),
  e("intake-workflow", "quality", "validate and gate", "control", ["mission"]),
  e("intake", "aurora-writer", "raw, curated, lineage", "data", ["mission"]),
  e("quality", "aurora-writer", "quality receipt", "evidence", ["mission"]),
  e("intake", "ticker", "activity receipt", "data", ["mission"]),
  e("http-api", "catalog", "catalog and lineage", "request", ["mission"]),
  e("http-api", "analytics", "run and inspect", "request", ["mission"]),
  e("http-api", "dashboard", "decision projection", "request", ["mission"]),
  e("http-api", "summarize", "summary and anomalies", "request", ["mission"]),
  e("http-api", "rag", "grounded question", "request", ["mission"]),
  e("http-api", "approvals", "review decision", "request", ["mission"]),
  e("http-api", "license", "license posture", "request", ["mission"]),
  e("http-api", "export", "governed release", "request", ["mission"]),
  e("http-api", "evidence", "system evidence", "request", ["mission", "operations"]),
  e("http-api", "rmf", "artifact request", "request", ["mission"]),
  e("catalog", "aurora-writer", "policy-aware read", "data", ["mission"]),
  e("analytics", "aurora-writer", "topics and model receipt", "data", ["mission"]),
  e("dashboard", "aurora-reader", "serving projection", "data", ["mission"]),
  e("summarize", "aurora-reader", "exceptions", "data", ["mission"]),
  e("rag", "aurora-reader", "RLS retrieval", "data", ["mission"]),
  e("approvals", "aurora-writer", "one-time decision", "data", ["mission"]),
  e("license", "aurora-reader", "license projection", "data", ["mission"]),
  e("export", "aurora-writer", "audit and release", "evidence", ["mission"]),
  e("evidence", "aurora-reader", "allowlisted proof", "evidence", ["mission", "operations"]),
  e("migrator", "aurora-writer", "migrations and seed", "control", ["mission", "operations"]),
  e("analytics", "bedrock", "embeddings and generation", "data", ["mission"]),
  e("summarize", "bedrock", "Nova Lite", "data", ["mission"]),
  e("rag", "bedrock", "grounded converse", "data", ["mission"]),
  e("scale-control", "scale-ledger", "plan and run state", "data", ["platform", "scale", "operations"], 2),
  e("scale-control", "scale-workflow", "start run", "control", ["platform", "scale", "operations"], 3),
  e("scale-workflow", "worker-queue", "partition messages", "control", ["platform", "scale", "operations"], 4),
  e("worker-queue", "scale-worker", "bounded work", "data", ["platform", "scale", "operations"], 5),
  e("worker-queue", "worker-dlq", "redrive", "evidence", ["scale", "operations"], 5),
  e("scale-worker", "scale-lake", "landing, curated, quarantine", "data", ["platform", "scale"], 6),
  e("scale-worker", "scale-ledger", "transactional receipt", "evidence", ["platform", "scale"], 5),
  e("scale-lake", "glue", "run partitions", "data", ["platform", "scale"], 7),
  e("lake-formation", "glue", "table permissions", "security", ["scale"], 7),
  e("glue", "athena", "six catalog tables", "data", ["platform", "scale"], 7),
  e("athena", "scale-lake", "Parquet output", "data", ["scale"], 7),
  e("athena", "scale-ledger", "query evidence", "evidence", ["platform", "scale", "operations"], 8),
  e("scale-ledger", "scale-control", "sanitized projection", "evidence", ["scale"], 8),
  e("scale-control", "export-queue", "export request", "control", ["platform", "scale", "operations"], 9),
  e("export-queue", "scale-export", "release job", "data", ["platform", "scale", "operations"], 9),
  e("export-queue", "export-dlq", "redrive", "evidence", ["scale", "operations"], 9),
  e("scale-export", "scale-lake", "release manifest", "evidence", ["scale"], 9),
  e("scale-export", "scale-ledger", "export receipt", "evidence", ["platform", "scale"], 9),
  e("cloudformation", "iam", "service roles", "security", ["security", "operations"]),
  e("github-actions", "terraform", "validated foundation plan", "control", ["security", "operations"]),
  e("terraform", "cloudformation", "reviewed application deployment", "control", ["security", "operations"]),
  e("cloudformation", "vpc", "declared network", "control", ["security"]),
  e("iam", "kms", "authorized cryptography", "security", ["security", "operations"]),
  e("vpc", "public-subnets", "two AZs", "control", ["security"]),
  e("vpc", "private-subnets", "two AZs", "control", ["security"]),
  e("internet-gateway", "public-subnets", "public route", "data", ["security"]),
  e("public-subnets", "nat-gateway", "managed egress", "data", ["security"]),
  e("private-subnets", "nat-gateway", "outbound TLS", "data", ["security"]),
  e("private-subnets", "lambda-sg", "function ENIs", "security", ["security"]),
  e("lambda-sg", "db-sg", "TCP 5432 only", "security", ["security"]),
  e("db-sg", "aurora-writer", "private writer", "security", ["security"]),
  e("db-sg", "aurora-reader", "private reader", "security", ["security"]),
  e("lambda-sg", "bedrock", "TLS via NAT", "data", ["security"]),
  e("secrets", "aurora-writer", "managed credential", "security", ["security"]),
  e("kms", "aurora-writer", "encrypted storage", "security", ["security"]),
  e("kms", "scale-lake", "SSE-KMS", "security", ["security", "operations"]),
  e("http-api", "cloudwatch-logs", "access logs", "evidence", ["operations"]),
  e("intake-workflow", "cloudwatch-logs", "workflow logs", "evidence", ["operations"]),
  e("scale-workflow", "cloudwatch-logs", "workflow logs", "evidence", ["operations"]),
  e("scale-control", "cloudwatch-logs", "application logs", "evidence", ["operations"]),
  e("scale-worker", "cloudwatch-logs", "worker metrics", "evidence", ["operations"]),
  e("cloudwatch-logs", "cloudwatch-alarms", "metrics", "evidence", ["operations"]),
  e("cloudwatch-alarms", "cloudwatch-dashboards", "health state", "evidence", ["operations"]),
  e("http-api", "xray", "trace segments", "evidence", ["operations"]),
  e("worker-queue", "cloudwatch-alarms", "depth and age", "evidence", ["operations"]),
  e("worker-dlq", "cloudwatch-alarms", "DLQ depth", "evidence", ["operations"]),
  e("export-dlq", "cloudwatch-alarms", "DLQ depth", "evidence", ["operations"]),
  e("guardduty", "securityhub", "findings", "security", ["security", "operations"]),
  e("macie", "securityhub", "findings", "security", ["security", "operations"]),
];

export const PLANE_META: Record<ArchitecturePlane, { label: string; color: string; tint: string }> = {
  access: { label: "Access", color: "#2563eb", tint: "#eff6ff" },
  control: { label: "Control", color: "#8c6a22", tint: "#fdf7e7" },
  compute: { label: "Compute", color: "#b45309", tint: "#fff7ed" },
  data: { label: "Data", color: "#1f7a8c", tint: "#ecfeff" },
  intelligence: { label: "Intelligence", color: "#6d4bb8", tint: "#f5f3ff" },
  evidence: { label: "Evidence", color: "#13704a", tint: "#ecfdf5" },
  security: { label: "Security", color: "#b42318", tint: "#fff1f2" },
  operations: { label: "Operations", color: "#475569", tint: "#f8fafc" },
};

export const FLOW_META: Record<FlowKind, { label: string; color: string; dash?: string }> = {
  request: { label: "Request", color: "#2563eb" },
  control: { label: "Control", color: "#8c6a22", dash: "7 5" },
  data: { label: "Data", color: "#0e7490" },
  evidence: { label: "Evidence", color: "#13704a", dash: "3 4" },
  security: { label: "Security", color: "#b42318", dash: "8 4" },
};

export function componentsForView(view: ArchitectureView): ArchitectureComponent[] {
  return COMPONENTS.filter((component) => component.positions[view]);
}

export function connectionsForView(view: ArchitectureView): ArchitectureConnection[] {
  const visible = new Set(componentsForView(view).map((component) => component.id));
  return CONNECTIONS.filter((connection) => connection.views.includes(view) && visible.has(connection.source) && visible.has(connection.target));
}
