export type RequirementSection = "PWS 4.3" | "PWS 4.4" | "PWS 6" | "PWS 9";

export type TraceStatus = "demonstrated" | "partial" | "roadmap";

export type RequirementTrace = {
  id: string;
  section: RequirementSection;
  sourcePage: number;
  title: string;
  requirement: string;
  capability: string;
  demoPath: string;
  demoLabel: string;
  workflow: string[];
  proof: string[];
  evidence: string[];
  status: TraceStatus;
  gap: string;
  tags: string[];
};

export const STATUS_META: Record<TraceStatus, { label: string; shortLabel: string; description: string }> = {
  demonstrated: {
    label: "Demonstrated prototype",
    shortLabel: "Demonstrated",
    description: "Implemented and directly showable with retained prototype evidence.",
  },
  partial: {
    label: "Implemented, proof incomplete",
    shortLabel: "Partial",
    description: "A working capability exists, but production evidence or part of the requirement is still incomplete.",
  },
  roadmap: {
    label: "Production roadmap",
    shortLabel: "Roadmap",
    description: "Not demonstrated as complete. This requires customer environment work, accreditation, or added implementation.",
  },
};

export const REQUIREMENT_SECTIONS: RequirementSection[] = ["PWS 4.3", "PWS 4.4", "PWS 6", "PWS 9"];

export const REQUIREMENTS: RequirementTrace[] = [
  {
    id: "diverse-st-sources",
    section: "PWS 4.3",
    sourcePage: 4,
    title: "Diverse S&T data acquisition",
    requirement: "Acquire and integrate data from diverse science and technology sources, including authorized commercial sources.",
    capability: "A source-adapter seam accepts canonical payloads into an immutable S3 landing zone. The accepted evidence package contains 177,503 minimized records across 12 public source families, while licensed, Government-furnished, and excluded sources have distinct activation states.",
    demoPath: "/intelligence/",
    demoLabel: "Source ledger",
    workflow: ["Open Source ledger.", "Verify the 12 collected public families and provenance state.", "Review the licensed, Government-furnished, and intentionally excluded acquisition groups."],
    proof: ["177,503-record accepted public corpus", "Source-level provenance and activation state", "Explicit license, Government access, and restricted-document boundaries"],
    evidence: ["public_intelligence/src/public_intelligence/registry.py", "frontend/lib/public-intelligence/source-acquisition.ts", "docs/PUBLIC_ONR_INTELLIGENCE.md"],
    status: "partial",
    gap: "No Government or licensed commercial source is connected. Advana, Pulse, restricted DTIC, Navy budget SharePoint, Government reports, and protected opportunity documents remain outside the collected public corpus.",
    tags: ["sources", "adapters", "S3", "public evidence", "acquisition boundary"],
  },
  {
    id: "quality-schema-drift",
    section: "PWS 4.3",
    sourcePage: 4,
    title: "Automated quality and schema drift",
    requirement: "Profile, cleanse, validate, and govern inputs while detecting anomalies, schema drift, and corrupt records at ingestion.",
    capability: "The intake workflow runs deterministic rule checks, recognizes compatible drift, quarantines incompatible batches, and retains rule-level Quality Receipts.",
    demoPath: "/ingest/",
    demoLabel: "Ingest and quality",
    workflow: ["Run the clean batch and inspect its passing receipt.", "Run compatible drift and show adapter normalization.", "Run incompatible drift and show quarantine with reasons."],
    proof: ["Rule-by-rule score", "Pass or quarantine decision", "Schema and adapter evidence"],
    evidence: ["src/functions/quality_gate/rules.py", "statemachines/intake.asl.yaml", "docs/BUILD_REPORT.md"],
    status: "demonstrated",
    gap: "Rules are proven against bounded synthetic fixtures, not the full variety or velocity of customer source systems.",
    tags: ["quality", "schema drift", "quarantine", "DataOps"],
  },
  {
    id: "catalog-dictionary-lineage",
    section: "PWS 4.3",
    sourcePage: 4,
    title: "Active catalog, dictionary, and lineage",
    requirement: "Provide an active data catalog, data dictionary, metadata management, and end-to-end lineage.",
    capability: "The governed catalog exposes freshness, quality, field definitions, originating batch, transformation steps, and an interactive lineage graph.",
    demoPath: "/catalog/",
    demoLabel: "Governed catalog",
    workflow: ["Open a dataset row and inspect its data dictionary.", "Review freshness and quality-gate evidence.", "Open lineage and trace source to decision use."],
    proof: ["Dataset and field metadata", "Quality and freshness state", "Clickable source-to-consumer lineage"],
    evidence: ["src/functions/catalog/app.py", "frontend/components/catalog/lineage-view.tsx", "docs/CONTRACTS.md"],
    status: "demonstrated",
    gap: "Lineage covers Compass workflows. Enterprise lineage across external tools requires their metadata integrations.",
    tags: ["catalog", "dictionary", "metadata", "lineage"],
  },
  {
    id: "analytics-ai-ml",
    section: "PWS 4.3",
    sourcePage: 4,
    title: "Advanced analytics and AI/ML",
    requirement: "Support advanced analytics, artificial intelligence, and machine learning against governed portfolio data.",
    capability: "Topic grouping, anomaly detection, grounded summaries, and portfolio decision projections are implemented behind a shared intelligence contract.",
    demoPath: "/analytics/",
    demoLabel: "Topic intelligence",
    workflow: ["Run topic intelligence over the governed portfolio.", "Open an anomaly and its contributing evidence.", "Compare model receipt and deterministic fallback disclosure."],
    proof: ["Topic and anomaly results", "Model or fallback receipt", "Grounding citations"],
    evidence: ["src/functions/analytics/topic_model.py", "src/common/python/compass_common/llm.py", "src/functions/rag_chat/retrieval.py"],
    status: "partial",
    gap: "Deterministic intelligence is proven. Final live Bedrock model-access confirmation remains a demo recording gate.",
    tags: ["analytics", "AI", "ML", "Bedrock"],
  },
  {
    id: "self-service-semantic-layer",
    section: "PWS 4.3",
    sourcePage: 4,
    title: "Self-service semantic layer",
    requirement: "Give users self-service access to curated analytics, a semantic layer, and a governed sandbox for exploration.",
    capability: "Role-aware dashboards, catalog projections, search, filters, standard APIs, and a governed portfolio vocabulary provide a consumer-facing semantic layer.",
    demoPath: "/dashboard/",
    demoLabel: "Decision brief",
    workflow: ["Filter the portfolio by topic, organization, and time.", "Switch personas and show scope changes.", "Follow a metric back to catalog and quality evidence."],
    proof: ["Stable business terms", "Role-aware metrics", "Filter and drill-through behavior"],
    evidence: ["frontend/components/dashboard/dashboard-view.tsx", "frontend/lib/mission-data-source.ts", "docs/CONTRACTS.md"],
    status: "partial",
    gap: "A customer-configurable report builder and governed notebook or sandbox environment are not implemented.",
    tags: ["self-service", "semantic layer", "dashboard", "sandbox"],
  },
  {
    id: "automated-ingestion",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Automated ingestion",
    requirement: "Automate ingestion through APIs, connectors, and file parsers with repeatable processing.",
    capability: "S3 events start an EventBridge-routed Step Functions intake workflow that normalizes, validates, curates, or quarantines each drop.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Start a batch in Ingest and quality.", "Open Mission control and follow its stage trace.", "Inspect the immutable correlation and terminal receipt."],
    proof: ["Event-driven stage trace", "Correlation chain", "Replayable source and terminal state"],
    evidence: ["template.yaml", "statemachines/intake.asl.yaml", "src/functions/intake/app.py"],
    status: "demonstrated",
    gap: "The prototype demonstrates file and API seams. Named customer SaaS, database, and streaming connectors still require configuration.",
    tags: ["ingestion", "API", "EventBridge", "Step Functions"],
  },
  {
    id: "unified-visualization",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Unified visualization",
    requirement: "Present operational, analytical, and decision information through a unified visualization experience.",
    capability: "Compass provides one responsive mission workspace across ingest, catalog, intelligence, decision, release, system evidence, and scale views.",
    demoPath: "/dashboard/",
    demoLabel: "Decision brief",
    workflow: ["Start with the executive decision brief.", "Drill into topic and anomaly evidence.", "Return through the persistent mission-flow navigation."],
    proof: ["Shared role and dataset context", "Accessible responsive views", "Traceable decision drill-down"],
    evidence: ["frontend/components/shell/app-shell.tsx", "frontend/components/dashboard/dashboard-view.tsx", "frontend/tests/e2e/demo-ready.spec.ts"],
    status: "demonstrated",
    gap: "Customer-defined dashboard authoring and external BI embedding are future integrations.",
    tags: ["visualization", "dashboard", "UX", "accessibility"],
  },
  {
    id: "workflow-automation",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Process and workflow automation",
    requirement: "Automate data, review, decision, and release workflows with auditable state transitions.",
    capability: "Express intake and Standard scale workflows coordinate data movement, quality gates, retries, quarantine, approvals, and governed exports.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Open the runtime stage trace.", "Switch to the workflow definition tab.", "Compare policy levers, receipts, and failure paths."],
    proof: ["Two deployed workflow definitions", "Retry and failure state", "Control and audit receipts"],
    evidence: ["statemachines/intake.asl.yaml", "statemachines/scale_run.asl.yaml", "STATUS.json"],
    status: "demonstrated",
    gap: "Customer approval chains and business process rules require discovery and configuration.",
    tags: ["automation", "workflow", "approvals", "audit"],
  },
  {
    id: "adaptive-scaling",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Adaptive scaling",
    requirement: "Scale platform features and processing capacity to changing workload volume.",
    capability: "The Scale Run Module uses cost-gated fixed profiles, partitioned SQS work, reserved-concurrency workers, a durable ledger, and lake-based outputs.",
    demoPath: "/admin/scale/",
    demoLabel: "Scale Lab",
    workflow: ["Preview a fixed scale profile and its cost ceiling.", "Launch the exact plan.", "Inspect partition, throughput, quality, cost, and export evidence."],
    proof: ["Accepted 1K through 1M profiles", "Partition and throughput receipts", "Bounded cost evidence"],
    evidence: ["src/functions/scale_runs/", "src/functions/scale_worker/", "docs/BUILD_REPORT.md"],
    status: "demonstrated",
    gap: "The evidence is a bounded synthetic acceptance run, not a sustained multi-terabyte or customer concurrency benchmark.",
    tags: ["scale", "SQS", "Lambda", "synthetic workload"],
  },
  {
    id: "secure-ui-api-export",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Secure UI, API, and bulk export",
    requirement: "Expose governed capabilities through secure user interfaces, standard APIs, and controlled bulk download.",
    capability: "CloudFront and WAF protect the UI, Cognito JWTs protect 25 API operations, and governed exports require authorization, scope checks, and four-eyes approval where applicable.",
    demoPath: "/export/",
    demoLabel: "Governed release",
    workflow: ["Choose an export format and scope.", "Trigger the independent approval path.", "Release once and inspect the checksummed receipt and audit trail."],
    proof: ["Protected OpenAPI contract", "Single-use approval", "Checksummed release receipt"],
    evidence: ["src/functions/export/openapi.py", "src/functions/export/app.py", "docs/SECURITY.md"],
    status: "demonstrated",
    gap: "Production transfer endpoints, data-loss prevention policy, and customer retention rules are not configured.",
    tags: ["UI", "API", "bulk export", "approval"],
  },
  {
    id: "iac-cicd",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Infrastructure as code and CI/CD",
    requirement: "Deliver repeatable infrastructure, automated testing, and continuous integration and deployment practices.",
    capability: "AWS SAM and CloudFormation define the stack. Repository workflows run quality checks and deployment steps using short-lived GitHub OIDC identity.",
    demoPath: "/admin/architecture/",
    demoLabel: "Architecture Explorer",
    workflow: ["Select Operations in the architecture.", "Inspect the versioned infrastructure and deployment boxes.", "Show tests, deployment receipts, rollback boundaries, and observability flows."],
    proof: ["Versioned SAM template", "Quality and deploy workflows", "Deployment revision projection"],
    evidence: ["template.yaml", ".github/workflows/quality.yml", ".github/workflows/deploy.yml"],
    status: "partial",
    gap: "An exact-commit CI deployment receipt and demonstrated zero-downtime rollback are still pending.",
    tags: ["IaC", "CI/CD", "CloudFormation", "GitHub OIDC"],
  },
  {
    id: "kinesis-streaming",
    section: "PWS 4.4",
    sourcePage: 5,
    title: "Streaming data transport",
    requirement: "Support streaming integration using Kinesis or Kafka-compatible patterns.",
    capability: "Kinesis Data Streams carries ordered operational activity receipts into the recent-activity projection while the governed database remains authoritative.",
    demoPath: "/ingest/",
    demoLabel: "Ingest and quality",
    workflow: ["Run an ingest batch.", "Watch activity events arrive in the ticker.", "Open Mission control and reconcile the event to the durable run receipt."],
    proof: ["Stream resource in deployed topology", "Stable event identifiers", "Database reconciliation path"],
    evidence: ["template.yaml", "src/functions/intake/pipeline.py", "frontend/components/ingest/stream-ticker.tsx"],
    status: "partial",
    gap: "The stream is deployed for operational events, but a sustained high-volume streaming benchmark and Kafka adapter are not demonstrated.",
    tags: ["Kinesis", "streaming", "events", "Kafka"],
  },
  {
    id: "open-modular-interoperability",
    section: "PWS 4.4",
    sourcePage: 6,
    title: "Modular open architecture and interoperability",
    requirement: "Use modular, loosely coupled services, standard interfaces, and portable data models that reduce vendor lock-in.",
    capability: "Narrow Lambda adapters, HTTP APIs, event contracts, queues, and independently durable stores separate the application, control, data, and evidence planes.",
    demoPath: "/admin/architecture/",
    demoLabel: "Architecture Explorer",
    workflow: ["Select Full platform and identify each plane.", "Toggle flow types to follow request, control, data, and evidence paths.", "Inspect recovery and interface contracts at any service box."],
    proof: ["Standard HTTP and event seams", "Portable JSON, CSV, and Parquet artifacts", "Independent queues and durable state"],
    evidence: ["docs/ARCHITECTURE.md", "docs/CONTRACTS.md", "template.yaml"],
    status: "demonstrated",
    gap: "Portability is designed and source-visible, but migration to a second cloud or Government platform has not been exercised.",
    tags: ["open architecture", "modular", "interoperability", "portability"],
  },
  {
    id: "mlops",
    section: "PWS 4.4",
    sourcePage: 6,
    title: "MLOps, model registry, and automated retraining",
    requirement: "Monitor drift and model decay, automate retraining and validation, maintain a model registry, and support dynamic GPU infrastructure.",
    capability: "A leakage-aware funding forecast uses authentic public USAspending quarters. A separate calibrated SBIR transition candidate trained on 11,287 authentic public examples in a network-isolated SageMaker job, was evaluated chronologically, sealed with source and artifact hashes, and registered as PendingManualApproval. Document-model controls expose candidate, approval, promotion, deployment, and drift receipts.",
    demoPath: "/intelligence/",
    demoLabel: "Public intelligence model evidence",
    workflow: ["Open Model evidence and identify the authentic target, temporal split, MAE, and interval coverage.", "Show that the package remains PendingManualApproval with no endpoint.", "Explain how an approved candidate would pass a human gate before deployment, monitoring, and retraining."],
    proof: ["Authentic public training rows", "Completed SageMaker training job", "Chronological holdout evidence", "Immutable hashes and model card", "SageMaker candidate registration without an endpoint"],
    evidence: ["public_intelligence/models/", "docs/PUBLIC_ONR_INTELLIGENCE.md", "src/functions/document_ml/app.py", "template.yaml"],
    status: "partial",
    gap: "The workflow proves bounded candidate training and registry control. Production validation, an approved endpoint, automated retraining triggers, sustained drift operations, and dynamic GPU provisioning are not demonstrated.",
    tags: ["MLOps", "model registry", "retraining", "GPU"],
  },
  {
    id: "devsecops-testing",
    section: "PWS 4.4",
    sourcePage: 6,
    title: "Automated testing and DevSecOps",
    requirement: "Automate functional and security validation through DevSecOps with controlled deployment and recovery.",
    capability: "Backend, contract, scenario, browser, accessibility, template, and CORS tests provide layered gates around the deployable source.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Open the deployment and health evidence.", "Show the tested API and workflow seams.", "Describe additive migrations and rollback handling."],
    proof: ["Automated test suites", "Health alarms and dashboards", "Versioned migrations and workflow definitions"],
    evidence: ["docs/BUILD_REPORT.md", ".github/workflows/quality.yml", "db/tests/"],
    status: "partial",
    gap: "STIG automation, zero-touch vulnerability scanning, and a measured zero-downtime deployment are not demonstrated.",
    tags: ["DevSecOps", "testing", "deployment", "recovery"],
  },
  {
    id: "finops",
    section: "PWS 4.4",
    sourcePage: 6,
    title: "FinOps and cost governance",
    requirement: "Track, forecast, constrain, and optimize cloud cost as part of platform operations.",
    capability: "Every Scale Plan calculates a price-backed ceiling before launch, then records planned and accrued estimates with workload evidence.",
    demoPath: "/admin/scale/",
    demoLabel: "Scale Lab",
    workflow: ["Preview a workload before launch.", "Compare cost ceiling, planned estimate, and accrued estimate.", "Inspect the immutable price and usage evidence."],
    proof: ["Pre-run cost gate", "Price snapshot", "Per-run accrued estimate"],
    evidence: ["src/common/python/compass_common/scale_cost.py", "docs/COST_MODEL.md", "scripts/fetch_aws_prices.py"],
    status: "partial",
    gap: "Displayed values are estimates, not reconciled AWS billing records, chargeback, or a monthly optimization program.",
    tags: ["FinOps", "cost", "budget", "pricing"],
  },
  {
    id: "dataops",
    section: "PWS 4.4",
    sourcePage: 6,
    title: "DataOps controls",
    requirement: "Operate repeatable data pipelines with quality validation, schema management, observability, and recoverable processing.",
    capability: "Immutable landing, schema adapters, quality gates, quarantine, idempotent partition receipts, correlation, metrics, alarms, and replay form the demonstrated DataOps loop.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Follow a batch from source hash to terminal state.", "Inspect quality, schema, retry, and quarantine evidence.", "Replay safely from the immutable source."],
    proof: ["End-to-end correlation", "Idempotent receipts", "Failure and replay evidence"],
    evidence: ["src/functions/intake/pipeline.py", "src/functions/scale_worker/", "src/functions/evidence/"],
    status: "demonstrated",
    gap: "Operating procedures are proven for the prototype boundary, not the Government production support organization.",
    tags: ["DataOps", "observability", "replay", "quality"],
  },
  {
    id: "government-qa-access",
    section: "PWS 4.4",
    sourcePage: 7,
    title: "Government QA and engineering access",
    requirement: "Give Government staff access to development, staging, production, source, configuration, and CI/CD evidence for independent quality assurance.",
    capability: "The deliverable contains source, IaC, migrations, tests, workflows, contracts, runbooks, and sanitized system evidence suitable for handoff and review.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Show deployed revision and health evidence.", "Map the runtime state to source and workflow definitions.", "Explain the proposed Government repository and environment access model."],
    proof: ["Source-complete handoff", "Configuration and workflow definitions", "Sanitized runtime evidence"],
    evidence: ["README.md", "docs/RUNBOOK.md", ".github/workflows/"],
    status: "roadmap",
    gap: "Government identities, repositories, environment roles, and dev, staging, and production access are not provisioned in this prototype account.",
    tags: ["Government access", "QA", "source", "environments"],
  },
  {
    id: "fedramp-il5-ato",
    section: "PWS 6",
    sourcePage: 13,
    title: "FedRAMP High, IL5, RMF, and ATO",
    requirement: "Operate in an authorized FedRAMP High and DoD IL5 environment and obtain an Authority to Operate through the RMF process.",
    capability: "The architecture includes security boundaries, encryption, private data services, access controls, audit evidence, and an RMF artifact-generation seam.",
    demoPath: "/admin/architecture/",
    demoLabel: "Architecture Explorer",
    workflow: ["Open Network and security.", "Trace identity, encryption, private data access, logging, and evidence controls.", "State the accreditation boundary clearly."],
    proof: ["Implemented prototype security controls", "RMF artifact endpoint seam", "Explicit non-accredited label"],
    evidence: ["docs/SECURITY.md", "src/functions/rmf_artifact/", "template.yaml"],
    status: "roadmap",
    gap: "The prototype is not FedRAMP High authorized, IL5 authorized, or covered by an ATO. Those outcomes require the Government environment and formal assessment.",
    tags: ["FedRAMP High", "IL5", "RMF", "ATO"],
  },
  {
    id: "rls-cls-aggregation",
    section: "PWS 6",
    sourcePage: 13,
    title: "Row, column, and AI access controls",
    requirement: "Enforce row-level and column-level security, address aggregation risk, and ensure AI responses inherit source-data permissions.",
    capability: "Aurora FORCE RLS, non-owner runtime roles, column grants, organization-scoped retrieval, protected funding fields, and aggregation checks constrain data and AI projections.",
    demoPath: "/dashboard/",
    demoLabel: "Decision brief",
    workflow: ["Switch from poweruser to scoped viewer.", "Show organization scope enforcement and protected funding values.", "Ask a governed question and inspect its scoped citations."],
    proof: ["FORCE RLS migration", "Column privilege policy", "Scope-aware retrieval and redaction"],
    evidence: ["db/migrations/002_rls.sql", "db/migrations/003_security_hardening.sql", "src/functions/rag_chat/retrieval.py"],
    status: "demonstrated",
    gap: "Policies are validated with synthetic organizations and roles, not customer attributes, classification guides, or an accredited boundary.",
    tags: ["RLS", "CLS", "aggregation", "AI security"],
  },
  {
    id: "least-privilege-mfa",
    section: "PWS 6",
    sourcePage: 14,
    title: "Zero trust, least privilege, and MFA",
    requirement: "Apply deny-by-default access, least privilege, multifactor authentication, and short-lived identity across users and services.",
    capability: "Cognito TOTP, short-lived JWTs, group-derived roles, a second claim verifier, scoped IAM roles, exact-origin CORS, and private database networking form the access path.",
    demoPath: "/admin/architecture/",
    demoLabel: "Architecture Explorer",
    workflow: ["Open Network and security.", "Trace the browser through Cognito, API Gateway, and the claim verifier.", "Inspect IAM, VPC, KMS, and private database boundaries."],
    proof: ["TOTP login path", "Deny-by-default identity contract", "Scoped service identities"],
    evidence: ["src/functions/authorizer/app.py", "frontend/lib/auth/identity-contract.ts", "template.yaml"],
    status: "demonstrated",
    gap: "Enterprise federation, PIV/CAC, and production identity lifecycle processes are not configured.",
    tags: ["zero trust", "least privilege", "MFA", "identity"],
  },
  {
    id: "compliance-stig-vulnerability",
    section: "PWS 6",
    sourcePage: 13,
    title: "Compliance as code, STIG, and vulnerability management",
    requirement: "Automate compliance evidence, STIG validation, RMF artifacts, vulnerability scanning, remediation, and patching.",
    capability: "Versioned infrastructure, security configuration, automated tests, audit projections, alarms, and an RMF artifact seam provide a foundation for compliance automation.",
    demoPath: "/admin/pipeline/",
    demoLabel: "Mission control",
    workflow: ["Show current health, audit, and deployment evidence.", "Open the architecture security view.", "Separate implemented controls from the planned compliance toolchain."],
    proof: ["Source-defined controls", "Sanitized audit evidence", "Explicit roadmap boundary"],
    evidence: ["docs/SECURITY.md", ".github/workflows/quality.yml", "src/functions/rmf_artifact/"],
    status: "roadmap",
    gap: "Automated STIG checks, zero-touch vulnerability scanning, patch SLAs, and a complete RMF evidence package are not demonstrated.",
    tags: ["compliance as code", "STIG", "vulnerability", "RMF"],
  },
  {
    id: "responsible-ai",
    section: "PWS 6",
    sourcePage: 14,
    title: "Responsible AI and AI TRiSM",
    requirement: "Apply AI trust, risk, and security management, safety filters, evaluation, red-team testing, and protection against sensitive disclosure.",
    capability: "Grounded retrieval, citations, allowlisted model identifiers, bounded prompts, scope inheritance, audit receipts, and deterministic fallback reduce current prototype risk.",
    demoPath: "/dashboard/",
    demoLabel: "Decision brief",
    workflow: ["Ask a governed portfolio question.", "Inspect citations, grounded status, and role scope.", "Explain the production evaluation and red-team gate."],
    proof: ["Grounding citations", "Model and fallback disclosure", "Role-scoped retrieval"],
    evidence: ["src/functions/rag_chat/rag.py", "src/functions/rag_chat/retrieval.py", "src/common/python/compass_common/disclosure.py"],
    status: "roadmap",
    gap: "Formal AI TRiSM governance, safety-filter certification, red-team campaigns, and continuous model evaluation are not demonstrated.",
    tags: ["Responsible AI", "AI TRiSM", "red team", "safety"],
  },
  {
    id: "open-formats-ownership",
    section: "PWS 9",
    sourcePage: 15,
    title: "Open formats, portability, and Government rights",
    requirement: "Keep data and deliverables portable, Government-accessible, and free from unnecessary proprietary lock-in using open, non-proprietary formats.",
    capability: "The system produces JSON, JSON Lines, CSV, and Parquet artifacts with checksums and manifests. Source, IaC, schemas, tests, and runbooks are part of the deliverable.",
    demoPath: "/export/",
    demoLabel: "Governed release",
    workflow: ["Choose a portable export format.", "Build the release and inspect manifest and checksum evidence.", "Use Architecture Explorer to show the API and storage seams."],
    proof: ["Portable data artifacts", "Checksummed manifest", "Source-complete architecture"],
    evidence: ["src/functions/export/app.py", "src/functions/scale_export/", "LICENSE"],
    status: "demonstrated",
    gap: "Government acceptance, data migration, and operation in the target NRE or NRDE environment have not yet occurred.",
    tags: ["open formats", "Parquet", "CSV", "JSON", "portability"],
  },
];

export function countByStatus(requirements: RequirementTrace[] = REQUIREMENTS): Record<TraceStatus, number> {
  return requirements.reduce<Record<TraceStatus, number>>(
    (counts, requirement) => ({ ...counts, [requirement.status]: counts[requirement.status] + 1 }),
    { demonstrated: 0, partial: 0, roadmap: 0 },
  );
}
