import type { IntelligenceSnapshot } from "./types";

export const PUBLIC_INTELLIGENCE_SNAPSHOT: IntelligenceSnapshot = {
  generatedAt: "2026-08-12T05:05:00Z",
  asOfDate: "2026-08-12",
  corpus: {
    awards: 13_300,
    contracts: 7_476,
    candidateAwardValueUsd: 19_260_405_492.79,
  },
  sources: [
    {
      id: "usaspending",
      name: "USAspending",
      authority: "U.S. Treasury",
      recordCount: 20_776,
      recordLabel: "retrieved candidate records in the persisted snapshot",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Department of the Navy plus keyword N00014 candidate scope. This is not an authoritative inventory of every ONR award.",
      url: "https://api.usaspending.gov/docs/endpoints",
    },
    {
      id: "crossref",
      name: "Crossref",
      authority: "Crossref Funder Registry",
      recordCount: 48_747,
      recordLabel: "ONR Funder Registry works persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "ONR Funder Registry works for publication outputs, citation metadata, funder assertions, and research impact. Publisher abstract text is withheld unless explicit reuse rights permit it.",
      url: "https://www.crossref.org/documentation/funder-registry/funder-data-via-the-api/",
    },
    {
      id: "openalex",
      name: "OpenAlex",
      authority: "OurResearch",
      recordCount: 68_912,
      recordLabel: "exact ONR funder-linked works persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Works linked to the Office of Naval Research funder identifier for concepts, institutions, citation graph, award identifiers, and the broader research landscape. Reconstructed abstracts are redacted when direct PII is detected.",
      url: "https://docs.openalex.org/api-entities/works",
    },
    {
      id: "pubmed",
      name: "PubMed",
      authority: "U.S. National Library of Medicine",
      recordCount: 1_595,
      recordLabel: "exact N00014[Grant Number] records persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Biomedical publications indexed with the exact N00014[Grant Number] query. PMID, DOI, PMCID, grant identifiers, journal, publication date, subject terms, and source links are retained. Researcher identities and copyrighted abstract text are omitted.",
      url: "https://pubmed.ncbi.nlm.nih.gov/?term=N00014%5BGrant+Number%5D",
    },
    {
      id: "osti",
      name: "OSTI.GOV",
      authority: "U.S. Department of Energy Office of Scientific and Technical Information",
      recordCount: 3_010,
      recordLabel: "exact ONR sponsor-filtered records persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Public technical reports, journal articles, datasets, and related research records returned by the exact Office of Naval Research sponsor organization filter. Researcher identities and description text are omitted pending rights review.",
      url: "https://www.osti.gov/api/v1/docs",
    },
    {
      id: "uspto-patents",
      name: "USPTO ODP patents",
      authority: "United States Patent and Trademark Office",
      recordCount: 5_388,
      recordLabel: "exact ONR government-interest patent grants persisted",
      status: "persisted",
      lastObserved: "2025-12-31",
      use: "Granted patents selected by an exact Office of Naval Research government-interest organization or a punctuation-folded N00014 award prefix. People, addresses, abstracts, and government-interest statement text are omitted. Source extraction remains subject to analyst review.",
      url: "https://data.uspto.gov/support/transition-guide/patentsview",
    },
    {
      id: "sbir",
      name: "SBIR and STTR",
      authority: "U.S. Small Business Administration",
      recordCount: 27_887,
      recordLabel: "Navy records in the minimized public snapshot",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Public Navy SBIR and STTR records for phase progression, topic labels, company outcomes, and authentic transition-target construction. Navy records are not assumed to be ONR records without an exact link.",
      url: "https://www.sbir.gov/data-resources",
    },
    {
      id: "grants-gov",
      name: "Grants.gov",
      authority: "U.S. Department of Health and Human Services",
      recordCount: 286,
      recordLabel: "DOD-ONR public opportunities persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Public ONR opportunity notices, dates, instruments, applicant types, program descriptions, and attachment lineage with contact fields removed.",
      url: "https://www.grants.gov/api",
    },
    {
      id: "sam_gov",
      name: "SAM.gov Opportunities",
      authority: "U.S. General Services Administration",
      recordCount: 5,
      recordLabel: "exact ONR hierarchy records in the bounded cache snapshot",
      status: "persisted",
      lastObserved: "2026-08-01",
      use: "A non-comprehensive subset recovered from 104 authorized public API cache pages limited to NAICS 541511, 541512, and 541519 after scanning 923 notices. Contacts, descriptions, attachment URLs, street addresses, ZIP codes, and API self links are omitted.",
      url: "https://open.gsa.gov/api/get-opportunities-public-api/",
    },
    {
      id: "datacite",
      name: "DataCite",
      authority: "DataCite",
      recordCount: 498,
      recordLabel: "ONR ROR-funded public outputs persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Public datasets and research outputs with ONR funding references, related identifiers, usage metadata, and rights evidence. Researcher identities and ORCIDs are omitted.",
      url: "https://support.datacite.org/docs/api",
    },
    {
      id: "onr-website",
      name: "Official ONR website index",
      authority: "Office of Naval Research",
      recordCount: 308,
      recordLabel: "official public sitemap headings persisted",
      status: "persisted",
      lastObserved: "2026-08-12",
      use: "Robots-aware collection of exact ONR public sitemap links, headings, hierarchy, page type, and Drupal node identifiers. Linked page bodies, documents, staff and contact pages, external links, and direct PII are omitted.",
      url: "https://www.onr.navy.mil/sitemap",
    },
    {
      id: "dtic",
      name: "DTIC grant awards",
      authority: "Defense Technical Information Center",
      recordCount: null,
      recordLabel: "public abstracts pending source profiling",
      status: "gated",
      lastObserved: "Not persisted",
      use: "Potential source for research abstracts and technical-report evidence when access and rights permit",
      url: "https://dodgrantawards.dtic.mil/grants",
    },
    {
      id: "federal-register",
      name: "Federal Register",
      authority: "National Archives and Records Administration",
      recordCount: 91,
      recordLabel: "Navy and ONR public notices persisted",
      status: "persisted",
      lastObserved: "2026-08-11",
      use: "Navy agency notices matching Office of Naval Research, with dockets, RINs, CFR references, dates, and official GovInfo links. Document bodies and public comments are not downloaded.",
      url: "https://www.federalregister.gov/developers/documentation/api/v1",
    },
  ],
  fundingFlow: [
    { fiscalYear: 2008, observedUsd: 1_007_249_559.99, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2009, observedUsd: 1_032_447_904.4, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2010, observedUsd: 1_019_595_813.89, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2011, observedUsd: 1_035_336_360.67, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2012, observedUsd: 1_052_023_957.34, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2013, observedUsd: 435_589_261.64, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2014, observedUsd: 451_521_887.21, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2015, observedUsd: 445_165_426.01, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2016, observedUsd: 551_373_752.88, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2017, observedUsd: 1_079_040_741.68, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2018, observedUsd: 1_175_728_109.6, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2019, observedUsd: 1_342_424_698.9, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2020, observedUsd: 1_415_828_776.4, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2021, observedUsd: 1_435_385_820.36, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2022, observedUsd: 1_540_685_661.58, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2023, observedUsd: 1_759_055_816.45, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2024, observedUsd: 1_754_927_606.18, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2025, observedUsd: 1_360_463_585.29, forecastUsd: null, lowerUsd: null, upperUsd: null },
    { fiscalYear: 2026, observedUsd: 912_973_221.97, forecastUsd: null, lowerUsd: null, upperUsd: null, isPartial: true },
  ],
  technologyAreas: [],
  programs: [
    {
      id: "N000142212041",
      title: "ONR ship time, technician and NDSF support 2021-2026",
      recipient: "Woods Hole Oceanographic Institution",
      source: "USAspending",
      sourceUrl: "https://www.usaspending.gov/award/ASST_NON_N000142212041_097",
      awardAmountUsd: 41_951_228.78,
      startDate: "2021-11-19",
      endDate: "2028-05-18",
      technologyArea: null,
      transitionProbability: null,
      impactPercentile: null,
      confidence: null,
      scopeNote: "Included because the award identifier contains N00014.",
      observedFacts: ["Award amount and recipient are present in the persisted USAspending snapshot.", "Award period is 2021-11-19 to 2028-05-18.", "The source description identifies ship time, technician, and NDSF support."],
    },
    {
      id: "N0001423C1022",
      title: "Future Advanced Strike (FAST) for ISR and precision strike capability",
      recipient: "Raytheon Company",
      source: "USAspending",
      sourceUrl: "https://www.usaspending.gov/award/CONT_AWD_N0001423C1022_9700_-NONE-_-NONE-",
      awardAmountUsd: 129_943_422,
      startDate: "2023-05-25",
      endDate: "2026-08-31",
      technologyArea: null,
      transitionProbability: null,
      impactPercentile: null,
      confidence: null,
      scopeNote: "Included because the award identifier contains N00014.",
      observedFacts: ["Award amount and recipient are present in the persisted USAspending snapshot.", "Award period is 2023-05-25 to 2026-08-31.", "The source description identifies ISR and precision strike capability."],
    },
    {
      id: "N0001422C1042",
      title: "Rapid and affordable software development supporting distributed maritime operations",
      recipient: "Innovative Defense Technologies, LLC",
      source: "USAspending",
      sourceUrl: "https://www.usaspending.gov/award/CONT_AWD_N0001422C1042_9700_-NONE-_-NONE-",
      awardAmountUsd: 99_133_463,
      startDate: "2022-04-01",
      endDate: "2026-09-30",
      technologyArea: null,
      transitionProbability: null,
      impactPercentile: null,
      confidence: null,
      scopeNote: "Included because the award identifier contains N00014.",
      observedFacts: ["Award amount and recipient are present in the persisted USAspending snapshot.", "Award period is 2022-04-01 to 2026-09-30.", "The source description identifies a prototype development environment for distributed maritime operations."],
    },
  ],
  models: [
    {
      id: "funding-forecast",
      name: "Funding flow forecast",
      objective: "Forecast the next observed quarterly obligation amount in the public candidate scope.",
      algorithm: "Random Forest with held-out conformal prediction interval",
      target: "Next-quarter observed obligations in the candidate scope",
      status: "candidate",
      metric: "Chronological holdout MAE",
      metricValue: 125_392_976.37,
      metricLabel: "$125.39M MAE; 85.71% empirical coverage for the nominal 90% interval",
      trainingRecords: 71,
      evidenceClass: "predicted",
      caveat: "Registered in SageMaker as PendingManualApproval. The small and volatile public series proves the governed training path, not production forecast accuracy. No endpoint is deployed, and forecast values are not budget commitments.",
    },
    {
      id: "transition",
      name: "SBIR transition probability",
      objective: "Estimate public Navy SBIR Phase I progression to a later public Phase II or III record using only information available at the prediction date.",
      algorithm: "Calibrated histogram gradient boosting with TF-IDF and SVD text features",
      target: "Observed public follow-on phase for the same organization and topic within 36 months",
      status: "candidate",
      metric: "Chronological holdout ROC AUC and Brier score",
      metricValue: 0.62642675,
      metricLabel: "0.626 ROC AUC; 0.262 Brier score; 2,260-record 2019 to 2023 holdout",
      trainingRecords: 11_287,
      evidenceClass: "predicted",
      caveat: "Trained in a network-isolated SageMaker job and registered as PendingManualApproval with no endpoint. The modest metrics do not establish production accuracy. Transition is an observable public proxy, not ONR mission success, causation, or an internal decision.",
    },
    {
      id: "topic",
      name: "Technology taxonomy classifier",
      objective: "Map award and publication text into a governed S&T taxonomy.",
      algorithm: "Proposed: domain text features plus calibrated classifier",
      target: "Historical SBIR topic or reviewed technology-area label",
      status: "not-trained",
      metric: "Macro F1",
      metricValue: null,
      metricLabel: "Not trained; reviewed taxonomy mapping is pending",
      trainingRecords: 0,
      evidenceClass: "derived",
      caveat: "Low-confidence assignments require analyst review.",
    },
    {
      id: "impact",
      name: "Research impact estimator",
      objective: "Estimate future research influence from award, publication, venue, institution, and citation-history features.",
      algorithm: "Proposed: hurdle or survival model with temporal censoring controls",
      target: "Field-normalized citation percentile after 24 months",
      status: "not-trained",
      metric: "Spearman correlation",
      metricValue: null,
      metricLabel: "Not trained; persisted publication evidence is pending",
      trainingRecords: 0,
      evidenceClass: "predicted",
      caveat: "Scholarly influence is only one dimension of mission impact.",
    },
    {
      id: "anomaly",
      name: "Portfolio anomaly detector",
      objective: "Surface unusual obligation, duration, concentration, and semantic patterns for human review.",
      algorithm: "Proposed: deterministic review rules plus Isolation Forest",
      target: "Unsupervised exception score",
      status: "not-trained",
      metric: "Precision at analyst review budget",
      metricValue: null,
      metricLabel: "Not trained; analyst adjudication is pending",
      trainingRecords: 0,
      evidenceClass: "predicted",
      caveat: "An anomaly is not evidence of fraud, waste, or failure.",
    },
  ],
};
